import {
  OpenRunde,
  fontInter,
  fontRoboto,
  fontOpenSans,
  fontManrope,
  fontGeist,
  fontRubik,
  fontDMSans,
  fontLato,
  fontRaleway,
  fontWorkSans,
  fontIBMPlexSans,
  fontFigtree,
  fontBricolage,
  fontHanken,
  fontLibreBaskerville,
  fontCrimsonPro,
} from '@/registry/lib/fonts/fonts'
import { TypographyPlaygroundClient, type PlaygroundFont } from './typography-interactive'

const fonts: PlaygroundFont[] = [
  {
    id: 'open-runde',
    name: 'Open Runde',
    category: 'Sans-serif',
    className: OpenRunde.className,
    variable: OpenRunde.variable,
    fontFamily: OpenRunde.style.fontFamily,
  },
  {
    id: 'inter',
    name: 'Inter',
    category: 'Sans-serif',
    className: fontInter.className,
    variable: fontInter.variable,
    fontFamily: fontInter.style.fontFamily,
  },
  {
    id: 'roboto',
    name: 'Roboto',
    category: 'Sans-serif',
    className: fontRoboto.className,
    variable: fontRoboto.variable,
    fontFamily: fontRoboto.style.fontFamily,
  },
  {
    id: 'open-sans',
    name: 'Open Sans',
    category: 'Sans-serif',
    className: fontOpenSans.className,
    variable: fontOpenSans.variable,
    fontFamily: fontOpenSans.style.fontFamily,
  },
  {
    id: 'manrope',
    name: 'Manrope',
    category: 'Sans-serif',
    className: fontManrope.className,
    variable: fontManrope.variable,
    fontFamily: fontManrope.style.fontFamily,
  },
  {
    id: 'geist',
    name: 'Geist',
    category: 'Sans-serif',
    className: fontGeist.className,
    variable: fontGeist.variable,
    fontFamily: fontGeist.style.fontFamily,
  },
  {
    id: 'rubik',
    name: 'Rubik',
    category: 'Sans-serif',
    className: fontRubik.className,
    variable: fontRubik.variable,
    fontFamily: fontRubik.style.fontFamily,
  },
  {
    id: 'dm-sans',
    name: 'DM Sans',
    category: 'Sans-serif',
    className: fontDMSans.className,
    variable: fontDMSans.variable,
    fontFamily: fontDMSans.style.fontFamily,
  },
  {
    id: 'lato',
    name: 'Lato',
    category: 'Sans-serif',
    className: fontLato.className,
    variable: fontLato.variable,
    fontFamily: fontLato.style.fontFamily,
  },
  {
    id: 'raleway',
    name: 'Raleway',
    category: 'Sans-serif',
    className: fontRaleway.className,
    variable: fontRaleway.variable,
    fontFamily: fontRaleway.style.fontFamily,
  },
  {
    id: 'work-sans',
    name: 'Work Sans',
    category: 'Sans-serif',
    className: fontWorkSans.className,
    variable: fontWorkSans.variable,
    fontFamily: fontWorkSans.style.fontFamily,
  },
  {
    id: 'ibm-plex-sans',
    name: 'IBM Plex Sans',
    category: 'Sans-serif',
    className: fontIBMPlexSans.className,
    variable: fontIBMPlexSans.variable,
    fontFamily: fontIBMPlexSans.style.fontFamily,
  },
  {
    id: 'figtree',
    name: 'Figtree',
    category: 'Sans-serif',
    className: fontFigtree.className,
    variable: fontFigtree.variable,
    fontFamily: fontFigtree.style.fontFamily,
  },
  {
    id: 'bricolage',
    name: 'Bricolage Grotesque',
    category: 'Grotesk',
    className: fontBricolage.className,
    variable: fontBricolage.variable,
    fontFamily: fontBricolage.style.fontFamily,
  },
  {
    id: 'hanken',
    name: 'Hanken Grotesk',
    category: 'Grotesk',
    className: fontHanken.className,
    variable: fontHanken.variable,
    fontFamily: fontHanken.style.fontFamily,
  },
  {
    id: 'libre-baskerville',
    name: 'Libre Baskerville',
    category: 'Serif',
    className: fontLibreBaskerville.className,
    variable: fontLibreBaskerville.variable,
    fontFamily: fontLibreBaskerville.style.fontFamily,
  },
  {
    id: 'crimson-pro',
    name: 'Crimson Pro',
    category: 'Serif',
    className: fontCrimsonPro.className,
    variable: fontCrimsonPro.variable,
    fontFamily: fontCrimsonPro.style.fontFamily,
  },
]

export function TypographyPlayground() {
  return <TypographyPlaygroundClient fonts={fonts} />
}
