export const DEFAULT_SEEDS = 'Space UI'

export const PERSONAS = [
  'Guillermo Rauch',
  'Marc Lou',
  'Pieter Levels',
  'Lauren Tam',
  'Alexander Wang',
  'Jony Ive',
  'Dieter Rams',
  'Steve Jobs',
  'Steve Wozniak',
  'Bill Gates',
  'Melinda French Gates',
  'Satya Nadella',
  'Sundar Pichai',
  'Tim Cook',
  'Craig Federighi',
  'Eddy Cue',
  'Johny Srouji',
  'Alan Dye',
  'Mike Matas',
  'Bret Victor',
  'John Gruber',
  'DHH',
  'David Heinemeier Hansson',
  'Jason Fried',
  'Tobias Lütke',
  'Tobi Lutke',
  'Shopify Tobi',
  'Patrick Collison',
  'John Collison',
  'Brian Chesky',
  'Joe Gebbia',
  'Nathan Blecharczyk',
  'Drew Houston',
  'Arash Ferdowsi',
  'Stewart Butterfield',
  'Cal Henderson',
  'Jack Dorsey',
  'Biz Stone',
  'Ev Williams',
  'Noah Glass',
  'Mark Zuckerberg',
  'Sheryl Sandberg',
  'Adam Mosseri',
  'Kevin Systrom',
  'Mike Krieger',
  'Brian Acton',
  'Jan Koum',
  'Reed Hastings',
  'Ted Sarandos',
  'Susan Wojcicki',
  'Larry Page',
  'Sergey Brin',
  'Eric Schmidt',
  'Jeff Bezos',
  'Andy Jassy',
  'Werner Vogels',
  'Elon Musk',
  'JB Straubel',
  'Tom Mueller',
  'Gwynne Shotwell',
  'Palmer Luckey',
  'John Carmack',
  'Gabe Newell',
  'Jensen Huang',
  'Lisa Su',
  'Pat Gelsinger',
  'Lisa Jackson',
  'Padmasree Warrior',
  'Reshma Saujani',
  'Tracy Chou',
  'Erica Baker',
  'Kimberly Bryant',
  'Arlan Hamilton',
  'Aileen Lee',
  'Jessica Livingston',
  'Paul Graham',
  'Trevor Blackwell',
  'Robert Morris',
  'Sam Altman',
  'Greg Brockman',
  'Ilya Sutskever',
  'Andrej Karpathy',
  'Demis Hassabis',
  'Shane Legg',
  'Mustafa Suleyman',
  'Dario Amodei',
  'Daniela Amodei',
  'Mira Murati',
  'Noam Shazeer',
  'Jeff Dean',
  'Sanjay Ghemawat',
  'Andrew Ng',
  'Fei-Fei Li',
  'Yann LeCun',
  'Geoffrey Hinton',
  'Yoshua Bengio',
  'Ian Goodfellow',
  'Chelsea Finn',
  'Pieter Abbeel',
  'Jim Fan',
  'Linus Torvalds',
  'Guido van Rossum',
  'Bjarne Stroustrup',
  'James Gosling',
  'Brendan Eich',
  'Ryan Dahl',
  'Bert Belder',
  'Isaac Schlueter',
  'TJ Holowaychuk',
  'Sindre Sorhus',
  'Addy Osmani',
  'Paul Irish',
  'Chris Coyier',
  'Sara Soueidan',
  'Lea Verou',
  'Rachel Andrew',
  'Jen Simmons',
  'Eric Meyer',
  'Jeffrey Zeldman',
  'Ethan Marcotte',
  'Brad Frost',
  'Dan Mall',
  'Sarah Drasner',
  'Sarah Bell',
  'Una Kravets',
  'Adam Argyle',
  'Jhey Tompkins',
  'Steve Schoger',
  'Adam Wathan',
  'Jonathan Reinink',
  'David Hemphill',
  'Taylor Otwell',
  'Evan You',
  'Sebastien Chopin',
  'Pooya Parsa',
  'Anthony Fu',
  'Daniel Roe',
  'Rich Harris',
  'True Gn',
  'Wes Bos',
  'Scott Tolinski',
  'Kent C. Dodds',
  'Dan Abramov',
  'Sophie Alpert',
  'Sebastian Markbåge',
  'Andrew Clark',
  'Jordan Walke',
  'Pete Hunt',
  'Christopher Chedeau',
  'Lee Robinson',
  'Delba de Oliveira',
  'Tim Neutkens',
  'JJ Kasper',
  'Shu Ding',
  'Jimmy Lai',
  'Malte Ubl',
  'Toby Miller',
  'Theo Browne',
  'T3 Theo',
  'ThePrimeagen',
  'Fireship',
  'Traversy Media',
  'Kevin Powell',
  'Josh Comeau',
  'Maggie Appleton',
  'Lin Clark',
  'Cassidy Williams',
  'Monica Powell',
  'Ire Aderinokun',
  'Una',
  'Sarah Federman',
  'Marcy Sutton',
  'Léonie Watson',
  'Heydon Pickering',
  'Adrian Roselli',
  "Scott O'Hara",
  'Eric Bailey',
  'Tatiana Mac',
  'Charlie Gerard',
  'Salma Alam-Naylor',
  'Whitep4nth3r',
  'Jason Lengstorf',
  'Swyx',
  'Shawn Wang',
  'Maggie',
  'Monica Lent',
  'Amelia Wattenberger',
  'Nadieh Bremer',
  'Shirley Wu',
  'Observable Mike',
  'Mike Bostock',
  'Philippe Rivière',
  'Bret Victor',
  'Lightship',
  'Toby Shorin',
  'Nadia Asparouhova',
  'Packy McCormick',
  'Lenny Rachitsky',
  'Andrew Chen',
  'Casey Winters',
  'Julie Zhuo',
  'John Cutler',
  'Teresa Torres',
  'Marty Cagan',
  'Melissa Perri',
  'Janna Bastow',
  'Matthew Strom',
  'Ryan Singer',
  'Jason Fried',
  'Basecamp Shape',
  'Bob Baxley',
  'Luke Wroblewski',
  'Jared Spool',
  'Don Norman',
  'Jakob Nielsen',
  'Bruce Tognazzini',
  'Alan Cooper',
  'Kim Goodwin',
  'Bill Buxton',
  'Bill Moggridge',
  'David Kelley',
  'Tom Kelley',
  'Tim Brown',
  'IDEO Tim',
  'Yves Béhar',
  'Karim Rashid',
  'Philippe Starck',
  'Naoto Fukasawa',
  'Jasper Morrison',
  'Marc Newson',
  'Ross Lovegrove',
  'Patricia Urquiola',
  'Hella Jongerius',
  'Ilse Crawford',
  'India Mahdavi',
  'Kelly Wearstler',
  'Virgil Abloh',
  'Matthew Williams',
  'Daniel Arsham',
  'Kanye Workshop',
  'Nigo',
  'Hiroshi Fujiwara',
  'James Jebbia',
  'Ferguson',
  'Tinker Hatfield',
  'Peter Saville',
  'Neville Brody',
  'Stefan Sagmeister',
  'Jessica Walsh',
  'Paula Scher',
  'Michael Bierut',
  'Massimo Vignelli',
  'Lella Vignelli',
  'Milton Glaser',
  'Paul Rand',
  'Saul Bass',
  'Susan Kare',
  'Rob Janoff',
  'Jonathan Hoefler',
  'Tobias Frere-Jones',
  'Matthew Carter',
  'Erik Spiekermann',
  'Jessica Hische',
  'Tobias van Schneider',
  'Jan Losert',
  'Meng To',
  'Dann Petty',
  'Ryan Putnam',
  'Rogie King',
  'Dribbble Dan',
  'Zack Onisko',
  'Tim Van Damme',
  'Piotr Świątkowski',
  'Cuberto',
  'Lusion',
  'Active Theory',
  'Resn',
  'Immersive Garden',
  'Locomotive',
  'Studio Freight',
  'Darkroom',
  'Pangram Pangram',
  'Klim Type',
  'Colophon Foundry',
  'Dinamo',
  'Grilli Type',
  'ABC Dinamo',
  'David Jonathan Ross',
  'Indra Kupferschmid',
  'Nina Stössinger',
  'Marcin Wichary',
  'Tobias Frere',
  'Bruno Simon',
  'Steven Wittens',
  'Ricardo Cabello',
  'Mr.doob',
  'Joshua Davis',
  'Casey Reas',
  'Ben Fry',
  'Lauren McCarthy',
  'Zach Lieberman',
  'Golan Levin',
  'Memo Akten',
  'Refik Anadol',
  'Mario Klingemann',
  'Sofia Crespo',
  'Anna Ridler',
  'Sougwen Chung',
  'Lauren Lee McCarthy',
  'Kyle McDonald',
  'Matt DesLauriers',
  'Tyler Hobbs',
  'Dmitri Cherniak',
  'Pak',
  'Beeple',
  'XCOPY',
  'Fewocious',
  'Hackatao',
  'Snowfro',
  'Erick Calderon',
  'Dom Hofmann',
  'Denis Nazarov',
  'Justin Blau',
  'Li Jin',
  'Packy',
  'Alex Danco',
  'Byrne Hobart',
  'Anu Atluru',
  'Sahil Lavingia',
  'Gumroad Sahil',
  'Daniel Vassallo',
  'Anthony Casalena',
  'David Cancel',
  'Hiten Shah',
  'Ryan Hoover',
  'Chris Messina',
  'Tom Preston-Werner',
  'Chris Wanstrath',
  'PJ Hyett',
  'Nat Friedman',
  'Thomas Dohmke',
  'Kyle Simpson',
  'Douglas Crockford',
  'Addy',
  'Paul Lewis',
  'Jake Archibald',
  'Surma',
  'Jason Miller',
  'Preact Jason',
  'Marvin Hagemeister',
  'Dominic Gannaway',
  'Sebastian McKenzie',
  'Devon Govett',
  'Devon',
  'Jamie Kyle',
  'Henry Zhu',
  'Nicolò Ribaudo',
  'Theodore Brown',
  'Fred K. Schott',
  'Nate Moore',
  'Matthew Phillips',
  'Sarah Rainsberger',
  'Ben Holmes',
  'Chris Schwieter',
  'Cassidy',
  'Tania Rascia',
  'Jessica Paoli',
  'Emma Bostian',
  'Ali Spittel',
  'Quincy Larson',
  'Beau Carnes',
  'Jessica Wilkins',
  'Jessica',
  'Ania Kubów',
  'Florin Pop',
  'Adrian Twarog',
  'Fireship Jeff',
  'Jeff Delaney',
  'David East',
  'Todd Motto',
  'Maximilian Schwarzmüller',
  'Academind',
  'Net Ninja',
  'Shaun Pelling',
  'The Net Ninja',
  'Traversy Brad',
  'Brad Traversy',
  'Programming with Mosh',
  'Mosh Hamedani',
  'Colt Steele',
  'Angela Yu',
  'Andrei Neagoie',
  'Zero To Mastery',
  'Sonny Sangha',
  'Clever Programmer',
  'Web Dev Simplified',
  'Kyle Cook',
  'Kevin Powell CSS',
  'Ahmad Shadeed',
  'Ahmad',
  'Josh W. Comeau',
  'Max Böck',
  'Andy Bell',
  'Piccalilli',
  'Heydon',
  'Every Layout',
  'Heydon Pickering',
  'Andy Budd',
  'Clearleft',
  'Jeremy Keith',
  'Adactio',
  'Remy Sharp',
  'Anna Debenham',
  'Charlotte Jackson',
  'Cennydd Bowles',
  'Cennydd',
  'Harry Roberts',
  'CSS Wizardry',
  'Chris Ferdinandi',
  'Go Make Things',
  'Dave Rupert',
  'Shop Talk',
  'Chris Coyier',
  'Robin Rendle',
  'Robin',
  'CSS-Tricks',
  'Sarah Drasner',
  'Sarah',
  'Sara Vieira',
  'Ives van Hoorne',
  'Bas Buursma',
  'CodeSandbox',
  'CodePen Chris',
  'Marie Cruz',
  'Kitty Giraudel',
  'Hugo Giraudel',
  'Kitty',
  'Zell Liew',
  'Ahmad Ajmi',
  'Osmani',
  'Paul Kinlan',
  'Thomas Steiner',
  'François Beaufort',
  'Pete LePage',
  'Ewa Gasperowicz',
  'Katie Hempenius',
  'Elizabeth Sweeny',
  'Houssein Djirdeh',
  'Jason Miller',
  'Jason',
  'Marvin',
  'Guillermo',
  'Malte',
  'Tim',
  'Lee',
  'Delba',
  'Shu',
  'Lydia Hallie',
  'Tania',
  'Cassidy Williams',
  'Sarah Bell',
  'Sarah Drasner Vue',
  'Evan',
  'Anthony',
  'Antfu',
  'Patak',
  'Patak Dev',
  'Daniel Roe',
  'Pooya',
  'Sébastien Chopin',
  'Alexandre Chopin',
  'Pooya Parsa',
  'Rahul Kadyan',
  'Johnson Chu',
  'Boshen',
  'Boshen Chen',
  'Alexander Lichter',
  'Michael Thiessen',
  'Lachlan Miller',
  'Eduardo San Martin Morote',
  'Posva',
  'Kia King',
  'Ben Hong',
  'Natalia Tepluhina',
  'Maria Santos',
  'Damian Dulisz',
  'Guillaume Chau',
  'Akryum',
  'Edd Yerburgh',
  'Chris Fritz',
  'Sarah Drasner',
  'Pinegrow',
  'Webflow Bryant',
  'Bryant Chou',
  'Vlad Magdalin',
  'Webflow',
  'Figma Dylan',
  'Dylan Field',
  'Evan Wallace',
  'Sho Kuwamoto',
  'Yuhki Yamashita',
  'Noah Levin',
  'Rasmus Andersson',
  'Sketch Pieter',
  'Pieter Omvlee',
  'Framer Koen',
  'Koen Bok',
  'Jorn van Dijk',
  'Niels van Hoorn',
  'Webflow Ma',
  'Notion Ivan',
  'Ivan Zhao',
  'Simon Last',
  'Akshay Kothari',
  'Linear Karri',
  'Karri Saarinen',
  'Tuomas Artman',
  'Jori Laukkanen',
  'Nan Yu',
  'Gavin Nelson',
  'Raycast Thomas',
  'Thomas Paul Mann',
  'Petr Zahara',
  'Superhuman Rahul',
  'Rahul Vohra',
  'Arc Josh',
  'Josh Miller',
  'Hursh Agrawal',
  'The Browser Company',
  'Spotify Daniel',
  'Daniel Ek',
  'Martin Lorentzon',
  'Gustav Söderström',
  'Airbnb Brian',
  'Stripe Patrick',
  'Stripe John',
  'Ludwig Pettersson',
  'Katie Dill',
  'Michael Bracken',
  'Michael',
  'Michael Flarup',
  'Pixelresort',
  'Sebastiaan de With',
  'IconFactory',
  'Louie Mantia',
  'David Lanham',
  'Iconfactory',
  'Michael Steeber',
  '9to5Mac',
  'Chance Miller',
  'Zac Hall',
  'Ryan Christoffel',
  'Filipe Espósito',
  'Juli Clover',
  'Jason Snell',
  'Six Colors',
  'Joe Steel',
  'Serenity Caldwell',
  'Myke Hurley',
  'Stephen Hackett',
  'Relay FM',
  'CGP Grey',
  'Brady Haran',
  'Marques Brownlee',
  'MKBHD',
  'iJustine',
  'Unbox Therapy',
  'Austin Evans',
  'Dave2D',
  'Linus Sebastian',
  'Luke Miani',
  'Max Tech',
  'Mrwhosetheboss',
  'Arun Maini',
  'MrWhoseTheBoss',
  'JerryRigEverything',
  'Zack Nelson',
  'iFixit Kyle',
  'Kyle Wiens',
  'Louis Rossmann',
  'Snazzy Labs',
  'Grant Thompson',
  'Kevin Rose',
  'Digg',
  'Revision3',
  'Leo Laporte',
  'This Week in Tech',
  'Jason Howell',
  'Mikah Sargent',
  'Ant Pruitt',
  'Alex Lindsay',
  'Paris Martineau',
  'Casey Newton',
  'Platformer',
  'Nilay Patel',
  'The Verge',
  'Dieter Bohn',
  'David Pierce',
  'Lauren Goode',
  'Zoe Schiffer',
  'Alex Heath',
  'Taylor Hatmaker',
  'Sarah Perez',
  'TechCrunch',
  'Michael Arrington',
  'Matthew Panzarino',
  'Ingrid Lunden',
  'Connie Loizos',
  'Natasha Mascarenhas',
  'Amanda Silberling',
  'Kirsten Korosec',
  'Darrell Etherington',
  'Frederic Lardinois',
  'Ron Miller',
  'Jordan Novet',
  'CNBC Jordan',
  'Steve Kovach',
  'Mark Gurman',
  'Bloomberg',
  'Wayne Ma',
  'The Information',
  'Jessica Lessin',
  'Martin Peers',
  'Amir Efrati',
  'Ankit Ajmera',
  'Kif Leswing',
  'Steve Troughton-Smith',
  'Steve T-S',
  'Guilherme Rambo',
  'Silver',
  'Mai',
  'Majid Jabrayilov',
  'Chris Lattner',
  'Ted Kremenek',
  'Joe Groff',
  'Doug Gregor',
  'Slava Pestov',
  'Becca Tory',
  'Holly Borla',
  'Ben Cohen',
  'Nate Chandler',
  'John Sundell',
  'Antoine van der Lee',
  'Paul Hudson',
  'Hacking with Swift',
  'Sean Allen',
  'Vincent Pradeilles',
  'Donny Wals',
  'Stewart Lynch',
  'Kavsoft',
  'Kavsoft SwiftUI',
  'Chris Eidhof',
  'Florian Kugler',
  'objc.io',
  'Airspeed Velocity',
  'Ole Begemann',
  'Nate Cook',
  'Soroush Khanlou',
  'Dave DeLong',
  'Matt Massicotte',
  'Peter Steinberger',
  'PSPDFKit',
  'Nik Fletcher',
  'Cocoatype',
  'Guy English',
  'Manton Reece',
  'Micro.blog',
  'Brent Simmons',
  'NetNewsWire',
  'Daniel Jalkut',
  'Red Sweater',
  'Craig Hockenberry',
  'Iconfactory Craig',
  'Gedeon Maheux',
  'Talos',
  'Panic Cabel',
  'Cabel Sasser',
  'Steven Frank',
  'Panic Steven',
  'Neven Mrgan',
  'Ash Furrow',
  'Orta Therox',
  'Felix Krause',
  'Fastlane',
  'KrauseFx',
  'Boris Bügling',
  'Javi Soto',
  'Nacho Soto',
  'Krzysztof Zabłocki',
  'Marcin Krzyzanowski',
  'Krzysztof',
  'Vadim Droznin',
  'Point-Free',
  'Brandon Williams',
  'Stephen Celis',
  'Chris Eidhof',
  'Thinking in SwiftUI',
  'objc',
  'Natalia Panferova',
  'Nil Coalescing',
  'Majid',
  'SwiftUI Majid',
  'Fatbobman',
  'Donny',
  'Antoine',
  'Stewart',
  'Sean',
  'Paul',
  'TwoStraws',
  'Kodeco',
  'Ray Wenderlich',
  'Audrey Tam',
  'raywenderlich',
  'Vicki Wenderlich',
  'Tammy Coron',
  'Richard Turton',
  'René Cacheaux',
  'James Dempsey',
  'James Dempsey Code',
  'Daniel Steinberg',
  'dimsumthinking',
  'Chris Adamson',
  'Daniel H Steinberg',
  'Matt Galloway',
  'Bart Jacobs',
  'Cocoacasts',
  'Aaron Hillegass',
  'Big Nerd Ranch',
  'Adam Preble',
  'Mikey Ward',
  'Juan Pablo Claude',
  'Bolot Kerimbaev',
  'Christian Keur',
  'Joe Conway',
  'Aaron',
  'Matt Thompson',
  'AFNetworking',
  'Sam Soffes',
  'Caleb Davenport',
  'thoughtbot',
  'Joe Ferris',
  'Chad Pytel',
  'Mike Burns',
  'Derek Prior',
  'Justin Searls',
  'Test Double',
  'Corey Haines',
  'Sarah Mei',
  'Sandi Metz',
  'Avdi Grimm',
  'Katrina Owen',
  'Exercism',
  'Josh Cheek',
  'Jim Weirich',
  'Dave Thomas',
  'Andy Hunt',
  'Pragmatic Programmers',
  'Uncle Bob',
  'Robert C. Martin',
  'Martin Fowler',
  'Kent Beck',
  'Ward Cunningham',
  'Ron Jeffries',
  'Alistair Cockburn',
  'Mike Cohn',
  'Jeff Sutherland',
  'Ken Schwaber',
  'Mary Poppendieck',
  'Tom Poppendieck',
  'Jez Humble',
  'Gene Kim',
  'Nicole Forsgren',
  'John Willis',
  'Patrick Debois',
  'Andrew Clay Shafer',
  'Kelsey Hightower',
  'Kelsey',
  'Bridget Kromhout',
  'Charity Majors',
  'Honeycomb',
  'Christine Yen',
  'Liz Fong-Jones',
  'Cindy Sridharan',
  'Sarah Wells',
  'Sarah',
  'Camille Fournier',
  'Will Larson',
  'Staff Eng',
  'Gergely Orosz',
  'Pragmatic Engineer',
  'Lara Hogan',
  ' tactica',
  'Michael Lopp',
  'Rands',
  'Julie Zhuo',
  'The Making of a Manager',
  'Kim Scott',
  'Radical Candor',
  'Ed Catmull',
  'Creativity Inc',
  'John Lasseter',
  'Pete Docter',
  'Andrew Stanton',
  'Brad Bird',
  'Lee Unkrich',
  'Domee Shi',
  'Encanto',
  'Byron Howard',
  'Jared Bush',
  'Jennifer Lee',
  'Chris Buck',
  'Fawn Veerasunthorn',
  'Peter Sohn',
  'Dan Scanlon',
  'Brian Fee',
  'Angus MacLane',
  'Enrico Casarosa',
  'Adrian Molina',
  'Domee',
  'Kelsey Mann',
  'Inside Out',
  'Pete',
  'Hayao Miyazaki',
  'Isao Takahata',
  'Toshio Suzuki',
  'Ghibli',
  'Makoto Shinkai',
  'Masaaki Yuasa',
  'Mamoru Hosoda',
  'Satoshi Kon',
  'Katsuhiro Otomo',
  'Hideaki Anno',
  'Shinichiro Watanabe',
  'Yoshiyuki Tomino',
  'Leiji Matsumoto',
  'Osamu Tezuka',
  'Naoko Takeuchi',
  'Akira Toriyama',
  'Eiichiro Oda',
  'Masashi Kishimoto',
  'Hajime Isayama',
  'Gege Akutami',
  'Koyoharu Gotouge',
  'Yoshihiro Togashi',
  'Hiromu Arakawa',
  'CLAMP',
  'Rumiko Takahashi',
  'Naoki Urasawa',
  'Takehiko Inoue',
  'Kentaro Miura',
  'Junji Ito',
  'Inio Asano',
  'Taiyo Matsumoto',
  'Jiro Taniguchi',
  'Katsuhiro',
  'Satoshi',
  'Makoto',
  'Hayao',
  'John Knoll',
  'Dennis Muren',
  'Phil Tippett',
  'Richard Edlund',
  'Douglas Trumbull',
  'Ray Harryhausen',
  "Willis O'Brien",
  'Stan Winston',
  'Rick Baker',
  'Rob Bottin',
  'Tom Savini',
  'Dick Smith',
  'Jack Pierce',
  'Lon Chaney',
  'Practical Effects',
  'ILM',
  'Weta Digital',
  'Joe Letteri',
  'Richard Taylor',
  'Peter Jackson',
  'Fran Walsh',
  'Philippa Boyens',
  'Andy Serkis',
  'Gollum',
  'Neill Blomkamp',
  'District 9',
  'Gareth Edwards',
  'Rogue One',
  'Denis Villeneuve',
  'Arrival',
  'Greig Fraser',
  'Roger Deakins',
  'Emmanuel Lubezki',
  'Hoyte van Hoytema',
  'Rachel Morrison',
  'Bradford Young',
  'James Laxton',
  'Ari Wegner',
  'Linus Sandgren',
  'Matthew Libatique',
  'Robert Elswit',
  'Janusz Kamiński',
  'Mandy Walker',
  'Darius Khondji',
  'Christopher Doyle',
  'Wong Kar-wai',
  'Park Chan-wook',
  'Bong Joon-ho',
  'Lee Isaac Chung',
  'Celine Song',
  'Chloe Zhao',
  'Greta Gerwig',
  'Noah Baumbach',
  'Wes Anderson',
  'Robert Yeoman',
  'Paul Thomas Anderson',
  'Jonny Greenwood',
  'Radiohead',
  'Thom Yorke',
  "Ed O'Brien",
  'Colin Greenwood',
  'Philip Selway',
  'Nigel Godrich',
  'Brian Eno',
  'Daniel Lanois',
  'Steve Albini',
  'Rick Rubin',
  'George Martin',
  'Quincy Jones',
  'Pharrell Williams',
  'Chad Hugo',
  'The Neptunes',
  'Timbaland',
  'Missy Elliott',
  'Kanye West',
  'Kid Cudi',
  'Travis Scott',
  'Frank Ocean',
  'Tyler the Creator',
  'Earl Sweatshirt',
  'Odd Future',
  'Steve Lacy',
  'Kevin Abstract',
  'Brockhampton',
  'Jaden Smith',
  'Willow Smith',
  'Donald Glover',
  'Childish Gambino',
  'Ludwig Göransson',
  'Michael Uzowuru',
  "Om'Mas Keith",
  'Romil Hemnani',
  'Kevin Parker',
  'Tame Impala',
  'Flume',
  'Harley Streten',
  'James Blake',
  'Four Tet',
  'Kieran Hebden',
  'Burial',
  'William Bevan',
  'Aphex Twin',
  'Richard D. James',
  'Boards of Canada',
  'Autechre',
  'Sean Booth',
  'Rob Brown',
  'Squarepusher',
  'Tom Jenkinson',
  'Flying Lotus',
  'Steven Ellison',
  'Thundercat',
  'Stephen Bruner',
  'Kamasi Washington',
  'Terrace Martin',
  'Robert Glasper',
  'Kendrick Lamar',
  'Sounwave',
  'Tae Beast',
  'Matt Schaeffer',
  'Alchemist',
  'Madlib',
  'J Dilla',
  'James Yancey',
  'Nujabes',
  'Jun Seba',
  'DJ Premier',
  'Pete Rock',
  'Large Professor',
  'Q-Tip',
  'Ali Shaheed Muhammad',
  'Phife Dawg',
  'Jarobi White',
  'A Tribe Called Quest',
  'The Roots',
  'Questlove',
  'Black Thought',
  'James Poyser',
  'Kamal Gray',
  'Captain Kirk Douglas',
  'Damon Albarn',
  'Jamie Hewlett',
  'Gorillaz',
  'Danger Mouse',
  'Brian Burton',
  'CeeLo Green',
  'Gnarls Barkley',
  'Jack White',
  'Meg White',
  'The White Stripes',
  'Patrick Carney',
  'Dan Auerbach',
  'The Black Keys',
  'Josh Homme',
  'Dave Grohl',
  'Taylor Hawkins',
  'Pat Smear',
  'Nate Mendel',
  'Chris Shiflett',
  'Rami Jaffee',
  'Foo Fighters',
  'Nirvana',
  'Kurt Cobain',
  'Krist Novoselic',
  'Pat Smear',
  'Pixies',
  'Black Francis',
  'Kim Deal',
  'Joey Santiago',
  'David Lovering',
  'Sonic Youth',
  'Thurston Moore',
  'Kim Gordon',
  'Lee Ranaldo',
  'Steve Shelley',
  'Pavement',
  'Stephen Malkmus',
  'Scott Kannberg',
  'Bob Nastanovich',
  'Mark Ibold',
  'Steve West',
  'Built to Spill',
  'Doug Martsch',
  'Modest Mouse',
  'Isaac Brock',
  'Eric Judy',
  'Jeremiah Green',
  'The Shins',
  'James Mercer',
  'Death Cab',
  'Ben Gibbard',
  'Chris Walla',
  'Nick Harmer',
  'Jason McGerr',
  'Postal Service',
  'Jimmy Tamborello',
  'The National',
  'Matt Berninger',
  'Aaron Dessner',
  'Bryce Dessner',
  'Bryan Devendorf',
  'Scott Devendorf',
  'Bon Iver',
  'Justin Vernon',
  'Sufjan Stevens',
  'Phoebe Bridgers',
  'Lucy Dacus',
  'Julien Baker',
  'boygenius',
  'Adrianne Lenker',
  'Big Thief',
  'Buck Meek',
  'Max Oleartchik',
  'James Krivchenia',
  'Japanese Breakfast',
  'Michelle Zauner',
  'Crying in H Mart',
  'Mitski',
  'Mitski Miyawaki',
  'Angel Olsen',
  'Weyes Blood',
  'Natalie Mering',
  'Faye Webster',
  'Clairo',
  'Claire Cottrill',
  'Beabadoobee',
  'Beatrice Laus',
  'Rex Orange County',
  "Alex O'Connor",
  'Steve Lacy',
  'Omar Apollo',
  'Cuco',
  'Omar Banos',
  'Kali Uchis',
  'Karly-Marina Loaiza',
  'Toro y Moi',
  'Chaz Bear',
  'Washed Out',
  'Ernest Greene',
  'Neon Indian',
  'Alan Palomo',
  'Mac DeMarco',
  'Unknown Mortal Orchestra',
  'Ruban Nielson',
  'King Krule',
  'Archy Marshall',
  'FKA twigs',
  'Tahliah Barnett',
  'Arca',
  'Alejandra Ghersi',
  'SOPHIE',
  'Sophie Xeon',
  'A. G. Cook',
  'PC Music',
  'Hannah Diamond',
  'GFOTY',
  'Danny L Harle',
  'Easyfun',
  'Lil Data',
  'QT',
  'Charli XCX',
  'Charlotte Aitchison',
  'Caroline Polachek',
  'Chairlift',
  'Blood Orange',
  'Devonté Hynes',
  'Solange',
  'Solange Knowles',
  'Beyoncé',
  'Beyonce Knowles',
  'Jay-Z',
  'Shawn Carter',
  'Rihanna',
  'Robyn Fenty',
  'The Weeknd',
  'Abel Tesfaye',
  'Drake',
  'Aubrey Graham',
  'The 1975',
  'Matty Healy',
  'George Daniel',
  'Adam Hann',
  'Ross MacDonald',
  'Arctic Monkeys',
  'Alex Turner',
  'Matt Helders',
  'Jamie Cook',
  "Nick O'Malley",
  'James Ford',
  'Jamie xx',
  'The xx',
  'Romy Madley Croft',
  'Oliver Sim',
  'Romy',
  'Sampha',
  'Sampha Sisay',
  'Kelela',
  'Kelela Mizanekristos',
  'FKA',
  'Sevdaliza',
  'Sevda Alizadeh',
  'Yaeji',
  'Kathy Lee',
  'Peggy Gou',
  'Kim Min-soo',
  'The Blaze',
  'Guillaume Alric',
  'Jonathan Alric',
  'Justice',
  'Gaspard Augé',
  'Xavier de Rosnay',
  'Daft Punk',
  'Thomas Bangalter',
  'Guy-Manuel de Homem-Christo',
  'Pedro Winter',
  'Busy P',
  'Ed Banger',
  'SebastiAn',
  'Sebastian Akchoté',
  'Breakbot',
  'Thibaut Berland',
  'Gesaffelstein',
  'Mike Lévy',
  'Kavinsky',
  'Vincent Belorgey',
  'M83',
  'Anthony Gonzalez',
  'Air',
  'Nicolas Godin',
  'Jean-Benoît Dunckel',
  'Phoenix',
  'Thomas Mars',
  "Deck d'Arcy",
  'Christian Mazzalai',
  'Laurent Brancowitz',
  'Cassius',
  'Philippe Zdar',
  'Hubert Blanc-Francard',
  'Laurent Garnier',
  'Jeff Mills',
  'Robert Hood',
  'Carl Craig',
  'Derrick May',
  'Juan Atkins',
  'Kevin Saunderson',
  'The Belleville Three',
  'Richie Hawtin',
  'Plastikman',
  'Sven Väth',
  'Paul van Dyk',
  'Armin van Buuren',
  'Tiësto',
  'Tijs Verwest',
  'Deadmau5',
  'Joel Zimmerman',
  'Skrillex',
  'Sonny Moore',
  'Diplo',
  'Thomas Wesley Pentz',
  'Major Lazer',
  'Walshy Fire',
  'Jillionaire',
  'Ape Drums',
  'RL Grime',
  'Henry Steinway',
  'Flume',
  'What So Not',
  'Chris Emerson',
  'Baauer',
  'Harry Rodrigues',
  'Hudson Mohawke',
  'Ross Birchard',
  'Rustie',
  'Russell Whyte',
  'Sophie',
  'A.G. Cook',
  'Danny L Harle',
  'Hannah Diamond',
  'QT',
  'GFOTY',
  'Easyfun',
  'Lifelike',
  'Lifelike Paris',
  'Kris Menace',
  'Kris',
  'Breakbot Irfane',
  'Irfane',
  'Chromeo',
  'David Macklovitch',
  'Patrick Gemayel',
  'P-Thugg',
  'Dave 1',
  'Theophilus London',
  'Kaytranada',
  'Louis Kevin Celestin',
  'Kaytra',
  'Sango',
  'Andrew Clay',
  'Masego',
  'Micah Davis',
  'Anderson .Paak',
  'Brandon Paak Anderson',
  'Silk Sonic',
  'Bruno Mars',
  'Peter Hernandez',
  'H.E.R.',
  'Gabriella Wilson',
  'SZA',
  'Solána Rowe',
  'Summer Walker',
  'Jhené Aiko',
  'Jhene Aiko Chilombo',
  'Kehlani',
  'Kehlani Parrish',
  'Daniel Caesar',
  'Ashton Simmonds',
  'Giveon',
  'Giveon Evans',
  'Brent Faiyaz',
  'Christopher Wood',
  'Steve Lacy',
  'Steve Thomas Lacy-Moya',
  'Fousheé',
  'Brittany Fousheé',
  'Arlo Parks',
  'Anaïs Marinho',
  'Lianne La Havas',
  'Lianne',
  'Celeste',
  'Celeste Waite',
  'Jorja Smith',
  'Jorja',
  'Mahalia',
  'Mahalia Burkmar',
  'Cleo Sol',
  'Cleo Solange',
  'SAULT',
  'Inflo',
  'Dean Josiah Cover',
  'Little Simz',
  'Simbiatu Ajikawo',
  'Michael Kiwanuka',
  'Michael',
  'Omar',
  'Omar Lye-Fook',
  "D'Angelo",
  'Michael Archer',
  'Erykah Badu',
  'Erica Wright',
  'Jill Scott',
  'Jill',
  'India.Arie',
  'India Arie Simpson',
  'Lauryn Hill',
  'Ms. Lauryn Hill',
  'Wyclef Jean',
  'Pras Michel',
  'Fugees',
  'Alicia Keys',
  'Alicia Augello Cook',
  'John Legend',
  'John Stephens',
  'Common',
  'Lonnie Lynn',
  'Talib Kweli',
  'Mos Def',
  'Yasiin Bey',
  'Dante Smith',
  'Black Star',
  'Hiatus Kaiyote',
  'Naomi Saalfield',
  'Nai Palm',
  'Paul Bender',
  'Simon Mavin',
  'Perrin Moss',
  'Khruangbin',
  'Laura Lee',
  'Mark Speer',
  'Donald Johnson',
  'Vulfpeck',
  'Jack Stratton',
  'Theo Katzman',
  'Woody Goss',
  'Joe Dart',
  'Antwaun Stanley',
  'Cory Wong',
  'Cory',
  'Mark Lettieri',
  'Snarky Puppy',
  'Michael League',
  'Bill Laurance',
  'Shaun Martin',
  'Justin Stanton',
  'Bob Reynolds',
  'Chris McQueen',
  'Bob Lanzetti',
  'Mark Lettieri',
  'Larnell Lewis',
  'Jamison Ross',
  'Jason Smart Thomas',
  'Nate Werth',
  'Jay Jennings',
  'Mike Maher',
  'Chris Bullock',
  'Keita Ogawa',
  'Marcel Camargo',
  'Mario Perez',
  'Zach Brock',
  'Tigran Hamasyan',
  'Tigran',
  'Brad Mehldau',
  'Brad',
  'Aaron Parks',
  'Aaron',
  'Robert Glasper',
  'Robert',
  'Terrace Martin',
  'Terrace',
  'Thundercat',
  'Stephen',
  'Kamasi',
  'Flying Lotus',
  'Steven',
  'Madlib',
  'Otis Jackson Jr.',
  'J Dilla',
  'James Dewitt Yancey',
  'Nujabes',
  'Jun',
  'DJ Shadow',
  'Josh Davis',
  'Cut Chemist',
  'Lucas MacFadden',
  'Nu-Mark',
  'Mark Potsic',
  'DJ Premier',
  'Christopher Martin',
  'Pete Rock',
  'Peter Phillips',
  'Large Professor',
  'William Paul Mitchell',
  'Q-Tip',
  'Kamaal Fareed',
  'Ali Shaheed',
  'Phife',
  'Malik Taylor',
  'Jarobi',
  'The Roots',
  'Ahmir Thompson',
  'Tariq Trotter',
  'James Poyser',
  'Kamal',
  'Captain Kirk',
  'Kirk Douglas',
  'Frank Knuckles',
  'Frank',
  'Tuba Gooding Jr.',
  'Damon Bryson',
  'Mark Kelley',
  'Mark',
  'Owen Biddle',
  'Owen',
  'Hub',
  'Leonard Hubbard',
  'Ben Kenney',
  'Ben',
  'Scratch',
  'Kyle Jones',
  'Dice Raw',
  'Karl Jenkins',
  'Black Thought',
  'Questlove',
  'Uma Sharma',
  'Pieter Levels',
  'Marc Lou',
  'Danny Postma',
  'Anthony Sistilli',
  'Tony Dinh',
  'Pim de Witte',
  'Andrey Azimov',
  'Ben Tossell',
  'Makerpad',
  'David Cramer',
  'Sentry',
  'Chris Nguyen',
  'Cal.com',
  'Peer Richelsen',
  'Bailey Pumfleet',
  'Crowdfunded',
  'Tibo',
  'Tibo from France',
  'Marc from Belgium',
  'Indie Worldwide',
  'Courtland Allen',
  'Indie Hackers',
  'James Bedell',
  'CJ',
  'James',
  'Anthony from Wingback',
  'Justin Jackson',
  'Transistor',
  'Jon Buda',
  'Marco Arment',
  'Overcast',
  'Instapaper',
  'John Gruber',
  'Daring Fireball',
  'Manton',
  'Craig Mod',
  'Craig',
  'Kevin Kelly',
  'Wired',
  'Stewart Brand',
  'Whole Earth',
  'Tim Ferriss',
  '4-Hour Workweek',
  'Derek Sivers',
  'CD Baby',
  'Seth Godin',
  'Purple Cow',
  'Ryan Holiday',
  'Daily Stoic',
  'James Clear',
  'Atomic Habits',
  'Cal Newport',
  'Deep Work',
  'Tiago Forte',
  'Building a Second Brain',
  'Ali Abdaal',
  'Ali',
  'Thomas Frank',
  "Matt D'Avella",
  'Yes Theory',
  'Ammar Kandil',
  'Thomas Brag',
  'Matt D',
  'Peter McKinnon',
  'Matti Haapoja',
  'Capturing Colour',
  'Parker Walbeck',
  'Gerald Undone',
  'Filmmaker IQ',
  'Indy Mogul',
  'Film Riot',
  'Ryan Connolly',
  'Dustin Tomanek',
  'Nathaniel Drew',
  'Nathaniel',
  'Chris Do',
  'The Futur',
  'Joey Ho',
  'Ben Burns',
  'The Futur Ben',
  'Kelli Anderson',
  'Jessica Walsh',
  'Sagmeister Walsh',
  'Stefan',
  'Jessica',
  'Paula',
  'Michael',
  'Pentagram',
  'Eddie Opara',
  'Marina Willer',
  'Nat Hunter',
  'Harry Pearce',
  'Domenic Lippa',
  'DJ Stout',
  'Justus Oehler',
  'Angus Hyland',
  'Luke Powell',
  'Jody Hudson-Powell',
  'Naresh Ramchandani',
  'Aporva Baxi',
  'Matt Baxter',
  'Rejane Dal Bello',
  'Sascha Lobe',
  'Yichu Sun',
  'Yehwan Song',
  'Yehwan',
  'Studio Yukiko',
  'Yukiko',
  'Ordinary Folk',
  'Nicolas Solerieu',
  'Nicolas',
  'Off+Brand',
  'Gavin Nelson',
  'Gavin',
  'Nelson Co',
  'Michael Flarup',
  'Pixelresort Michael',
  'Sebastiaan',
  'IconFactory Louie',
  'Louie',
  'David Lanham',
  'Talos',
  'Neven',
  'Cabel',
  'Steven Frank',
  'Panic',
  'Transmit',
  'Coda',
  'Nova',
  'Playdate',
  'Panic Playdate',
  'Shaun Inman',
  'Shaun',
  'Mint',
  'Fever',
  'Capo',
  'Typeeto',
  'Pinner',
  'Clicker',
  'Have I Been Pwned',
  'Troy Hunt',
  'Troy',
  'Scott Hanselman',
  'Scott',
  'Jeff Atwood',
  'Coding Horror',
  'Joel Spolsky',
  'Joel on Software',
  'Fog Creek',
  'Stack Overflow',
  'Trello',
  'Glitch',
  'Anil Dash',
  'Anil',
  'Gina Trapani',
  'Gina',
  'Lifehacker',
  'Merlin Mann',
  '43 Folders',
  'John Gruber',
  'Daring',
  'Jason Kottke',
  'Kottke',
  'Andy Baio',
  'Waxy',
  'XOXO',
  'Andy',
  'Matt Haughey',
  'MetaFilter',
  'Matt',
  'Joshua Schachter',
  'Delicious',
  'Joshua',
  'Thomas Vander Wal',
  'Folksonomy',
  'Clay Shirky',
  'Clay',
  'Caterina Fake',
  'Flickr',
  'Caterina',
  'Stewart Butterfield',
  'Flickr Stewart',
  'Slack',
  'Cal Henderson',
  'Eric Costello',
  'George Oates',
  'George',
  'Heather Champ',
  'Heather',
  'Aaron Straup Cope',
  'Aaron',
  'Dan Cederholm',
  'SimpleBits',
  'Dribbble Dan',
  'Rich Thornett',
  'Rich',
  'Dribbble',
  'Zack Onisko',
  'Zack',
  'Tim Van Damme',
  'Tim',
  'Piotr',
  'Maxime Heckel',
  'Maxime',
  'Josh Comeau',
  'Josh',
  'Maggie Appleton',
  'Maggie',
  'Lin Clark',
  'Lin',
  'Surma',
  'Jake',
  'Paul Irish',
  'Addy Osmani',
  'Addy',
  'Paul Lewis',
  'Aerotwist',
  'Rachel Nabors',
  'Rachel',
  'Val Head',
  'Val',
  'Sarah Drasner',
  'Sarah',
  'Cassie Evans',
  'Cassie',
  'GSAP GreenSock',
  'Jack Doyle',
  'Carl Schooff',
  'OSUblake',
  'Blake Bowen',
  'Petr Tichy',
  'Ihatetomatoes',
  'Lusi',
  'Olivier Larose',
  'Olivier',
  'Minh Pham',
  'Minh',
  'Locomotive',
  'Etienne Pouliot',
  'Etienne',
  'Christophe Ouellette',
  'Christophe',
  'Eduard Bodak',
  'Eduard',
  'Aristide Benoist',
  'Aristide',
  'Martin Laxenaire',
  'Martin',
  'Bruno Simon',
  'Bruno',
  'Three.js Journey',
  'David Ronai',
  'David',
  'Yasai',
  'Yasai.jp',
  'Akira Calzadilla',
  'Akira',
  'Jaume Sanchez',
  'Jaume',
  'Clicktorelease',
  'Ricardo Cabello',
  'Mrdoob',
  'Joshua',
  'Joshua Davis',
  'Praystation',
  'Brendan Dawes',
  'Brendan',
  'Robert Hodgin',
  'Flight404',
  'Robert',
  'Memo Akten',
  'Memo',
  'Zach Lieberman',
  'Zach',
  'Golan',
  'Lauren McCarthy',
  'p5.js',
  'Casey Reas',
  'Ben Fry',
  'Processing',
  'Daniel Shiffman',
  'The Coding Train',
  'Shiffman',
  'Hartmut Bohnacker',
  'Benedikt Groß',
  'Julia Laub',
  'Claudius Lazzeroni',
  'Generative Design',
  'Matt DesLauriers',
  'Matt',
  'canvas-sketch',
  'Tyler Hobbs',
  'Fidenza',
  'Tyler',
  'Dmitri Cherniak',
  'Ringers',
  'Dmitri',
  'Snowfro',
  'Art Blocks',
  'Erick Calderon',
  'Erick',
  'Dom Hofmann',
  'Vine',
  'Byte',
  'Dom',
  'Denis Nazarov',
  'Zora',
  'Denis',
  'Justin Blau',
  '3LAU',
  'Justin',
  'Li Jin',
  'Variant',
  'Li',
  'Packy McCormick',
  'Not Boring',
  'Packy',
  'Anu Atluru',
  'Anu',
  'Alex Danco',
  'Alex',
  'Byrne Hobart',
  'The Diff',
  'Byrne',
  'Sahil Lavingia',
  'Gumroad',
  'Sahil',
  'Daniel Vassallo',
  'Daniel',
  'Anthony Casalena',
  'Squarespace',
  'Anthony',
  'David Cancel',
  'Drift',
  'David',
  'Hiten Shah',
  'Hiten',
  'Ryan Hoover',
  'Product Hunt',
  'Ryan',
  'Chris Messina',
  'Hashtag',
  'Chris',
  'Tom Preston-Werner',
  'Tom',
  'mojombo',
  'Chris Wanstrath',
  'defunkt',
  'PJ Hyett',
  'pjhyett',
  'Nat Friedman',
  'Nat',
  'Thomas Dohmke',
  'GitHub',
  'Thomas',
  'Kyle Simpson',
  "You Don't Know JS",
  'getify',
  'Douglas Crockford',
  'Crockford',
  'Addy Osmani',
  'Paul Irish',
  'Jake Archibald',
  'Surma',
  'Jason Miller',
  '_developit',
  'Marvin Hagemeister',
  'marvinhagemeister',
  'Dominic Gannaway',
  'trueadm',
  'Sebastian McKenzie',
  'kittens',
  'Devon Govett',
  'devongovett',
  'Parcel',
  'Jamie Kyle',
  'jamiebuilds',
  'Henry Zhu',
  'hzoo',
  'Babel',
  'Nicolò Ribaudo',
  'nicolo-ribaudo',
  'Fred K. Schott',
  'Fred',
  'Snowpack',
  'Astro',
  'Nate Moore',
  'natemoo-re',
  'Matthew Phillips',
  'matthewcp',
  'Sarah Rainsberger',
  'Sarah',
  'Ben Holmes',
  'bholmesdev',
  'Chris Schwieter',
  'Chris',
  'Tania Rascia',
  'taniarascia',
  'Emma Bostian',
  'embostian',
  'Ali Spittel',
  'aspittel',
  'Quincy Larson',
  'freeCodeCamp',
  'Quincy',
  'Beau Carnes',
  'Beau',
  'Jessica Wilkins',
  'Jessica',
  'Ania Kubów',
  'Ania',
  'Florin Pop',
  'florinpop17',
  'Adrian Twarog',
  'Adrian',
  'Jeff Delaney',
  'codediodeio',
  'Fireship',
  'David East',
  'davideast',
  'Todd Motto',
  'toddmotto',
  'Maximilian Schwarzmüller',
  'Academind Max',
  'Shaun Pelling',
  'NetNinja',
  'Brad Traversy',
  'traversymedia',
  'Mosh Hamedani',
  'programmingwithmosh',
  'Colt Steele',
  'The Colt Steele',
  'Angela Yu',
  'App Brewery',
  'Andrei Neagoie',
  'ZeroToMastery',
  'Sonny Sangha',
  'CleverProgrammer',
  'Kyle Cook',
  'WebDevSimplified',
  'Kevin Powell',
  'kevin-powell',
  'Ahmad Shadeed',
  'ishadeed',
  'Josh Comeau',
  'joshwcomeau',
  'Max Böck',
  'mxbck',
  'Andy Bell',
  'hankchizljaw',
  'piccalil.li',
  'Jeremy Keith',
  'adactio',
  'Remy Sharp',
  'rem',
  'Dave Rupert',
  'davatron5000',
  'Harry Roberts',
  'csswizardry',
  'Chris Ferdinandi',
  'cferdinandi',
  'Robin Rendle',
  'robinrendle',
  'Sara Vieira',
  'NikkitaFTW',
  'Ives van Hoorne',
  'CompuIves',
  'CodeSandbox Ives',
  'Kitty Giraudel',
  'KittyGiraudel',
  'Zell Liew',
  'zellwk',
  'Adam Argyle',
  'argyleink',
  'Jhey Tompkins',
  'jh3yy',
  'Steve Schoger',
  'steveschoger',
  'Adam Wathan',
  'adamwathan',
  'Jonathan Reinink',
  'reinink',
  'Taylor Otwell',
  'taylorotwell',
  'Laravel',
  'Evan You',
  'yyx990803',
  'Vue',
  'Vite',
  'Anthony Fu',
  'antfu',
  'Vitest',
  'UnoCSS',
  'Slidev',
  'Rich Harris',
  'Rich-Harris',
  'Svelte',
  'SvelteKit',
  'Wes Bos',
  'wesbos',
  'Scott Tolinski',
  'stolinski',
  'Syntax',
  'Kent C. Dodds',
  'kentcdodds',
  'Testing Library',
  'Dan Abramov',
  'gaearon',
  'Redux',
  'Sophie Alpert',
  'sophiebits',
  'Sebastian Markbåge',
  'sebmarkbage',
  'Andrew Clark',
  'acdlite',
  'Jordan Walke',
  'jordwalke',
  'Pete Hunt',
  'petehunt',
  'Christopher Chedeau',
  'vjeux',
  'Lee Robinson',
  'leerob',
  'Delba de Oliveira',
  'delbaoliveira',
  'Tim Neutkens',
  'timneutkens',
  'JJ Kasper',
  'ijjk',
  'Shu Ding',
  'shuding',
  'Malte Ubl',
  'cramforce',
  'Theo Browne',
  't3dotgg',
  'T3 Stack',
  'ThePrimeagen',
  'ThePrimeagen Neovim',
  'Lydia Hallie',
  'lydiahallie',
  'Cassidy Williams',
  'cassidoo',
  'Swyx',
  'swyx',
  'Shawn Wang',
  'Jason Lengstorf',
  'jlengstorf',
  'Salma Alam-Naylor',
  'whitep4nth3r',
  'Charlie Gerard',
  'devdevcharlie',
  'Monica Powell',
  'M0nica',
  'Ire Aderinokun',
  'ireaderinokun',
  'Marcy Sutton',
  'marcysutton',
  'Léonie Watson',
  'Leoniewatson',
  'Adrian Roselli',
  'aardrian',
  "Scott O'Hara",
  'scottohara',
  'Tatiana Mac',
  'TatianaTMac',
  'Amelia Wattenberger',
  'Wattenberger',
  'Nadieh Bremer',
  'Nadieh',
  'Shirley Wu',
  'sxywu',
  'Mike Bostock',
  'mbostock',
  'D3',
  'Observable',
  'Nadia Asparouhova',
  'nayafia',
  'Working in Public',
  'Lenny Rachitsky',
  'lennysan',
  "Lenny's Newsletter",
  'Andrew Chen',
  'andrewchen',
  'Casey Winters',
  'Casey',
  'John Cutler',
  'johncutlefish',
  'Teresa Torres',
  'ttorres',
  'Marty Cagan',
  'cagan',
  'Inspired',
  'Melissa Perri',
  'melissaperri',
  'Escaping the Build Trap',
  'Ryan Singer',
  'rjs',
  'Shape Up',
  'Luke Wroblewski',
  'lukew',
  'Mobile First',
  'Jared Spool',
  'jmspool',
  'Don Norman',
  'jnd1er',
  'The Design of Everyday Things',
  'Jakob Nielsen',
  'nngroup',
  'Nielsen Norman',
  'Alan Cooper',
  'About Face',
  'Kim Goodwin',
  'Designing for the Digital Age',
  'Bill Buxton',
  'Sketching User Experiences',
  'David Kelley',
  'IDEO',
  'Tim Brown',
  'Change by Design',
  'Yves Béhar',
  'Fuseproject',
  'Karim Rashid',
  'Karim',
  'Naoto Fukasawa',
  'Naoto',
  'Jasper Morrison',
  'Jasper',
  'Marc Newson',
  'Marc',
  'Patricia Urquiola',
  'Patricia',
  'Ilse Crawford',
  'Ilse',
  'India Mahdavi',
  'India',
  'Kelly Wearstler',
  'Kelly',
  'Virgil Abloh',
  'Off-White',
  'Matthew Williams',
  '1017 ALYX 9SM',
  'Daniel Arsham',
  'Snarkitecture',
  'Hiroshi Fujiwara',
  'Fragment Design',
  'Nigo',
  'A Bathing Ape',
  'James Jebbia',
  'Supreme',
  'Tinker Hatfield',
  'Air Jordan',
  'Peter Saville',
  'Factory Records',
  'Neville Brody',
  'The Face',
  'Susan Kare',
  'Macintosh Icons',
  'Rob Janoff',
  'Apple Logo',
  'Paul Rand',
  'IBM',
  'Saul Bass',
  'Otto Preminger',
  'Milton Glaser',
  'I Love NY',
  'Massimo Vignelli',
  'NYC Subway',
  'Lella Vignelli',
  'Vignelli Associates',
  'Paula Scher',
  'Public Theater',
  'Michael Bierut',
  'Design Observer',
  'Jessica Hische',
  'Drop Cap',
  'Jessica Walsh',
  ' sagmeisterwalsh',
  'Stefan Sagmeister',
  'Things I Have Learned',
  'Tobias van Schneider',
  'Semplice',
  'Jan Losert',
  'Jan',
  'Meng To',
  'Design+Code',
  'Dann Petty',
  'Designer Secrets',
  'Rogie King',
  'Rogie',
  'Cuberto',
  'Cuberto Agency',
  'Lusion',
  'Lusion.co',
  'Active Theory',
  'ActiveTheory',
  'Resn',
  'Resn Wellington',
  'Immersive Garden',
  'Locomotive Montreal',
  'Studio Freight',
  'Darkroom.engineering',
  'Pangram Pangram',
  'Klim Type Foundry',
  'Kris Sowersby',
  'Colophon Foundry',
  'Dinamo Type',
  'Johannes Breyer',
  'Fabian Harb',
  'Grilli Type',
  'Noel Leu',
  'Thierry Blancpain',
  'ABC Dinamo',
  'David Jonathan Ross',
  'DJR',
  'Indra Kupferschmid',
  'Indra',
  'Nina Stössinger',
  'Nina',
  'Marcin Wichary',
  'Shift Happens',
  'Marcin',
  'Jonathan Hoefler',
  'Hoefler&Co',
  'Tobias Frere-Jones',
  'Frere-Jones Type',
  'Matthew Carter',
  'Georgia Verdana',
  'Erik Spiekermann',
  'MetaFont',
  'FF Meta',
]

export const HISTORICAL_PERSONAS = PERSONAS
