import type { Metadata } from 'next'
import Link from 'next/link'
import { Badge } from '@/registry/components/spaceui/badge-squircle'
import { Button } from '@/registry/components/spaceui/button-squircle'
import { DocsPager } from '@/components/docs/layout/docs-pager'
import { siteConfig } from '@/config/space-config'
import { TypeTable } from '@/components/docs/mdx/type-table'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description:
    'Learn how Space UI collects, handles, and protects your information when using our documentation, component registry, and Community Wall.',
}

export default function PrivacyPolicyPage() {
  return (
    <div className="flex flex-col gap-8 text-foreground">
      {/* Breadcrumb */}
      <nav aria-label="Breadcrumb" className="flex items-center gap-2 text-xs text-muted-foreground">
        <Link href="/" className="hover:text-foreground transition-colors">
          Home
        </Link>
        <span>/</span>
        <span>Legal</span>
        <span>/</span>
        <span className="font-medium text-foreground">Privacy Policy</span>
      </nav>

      {/* Header */}
      <header className="flex flex-col gap-3 pb-4">
        <div className="flex flex-wrap items-center gap-2">
          <Badge size="sm">Privacy Policy</Badge>
          <span className="text-xs text-muted-foreground">v1.0.0</span>
          <span className="text-muted-foreground">·</span>
          <span className="text-xs text-muted-foreground">Last updated: September 15, 2026</span>
        </div>

        <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-foreground">Privacy Policy</h1>
        <p className="text-base sm:text-lg text-muted-foreground leading-relaxed">
          Our commitment to transparency, data minimization, and user privacy for developers, creators, and contributors
          across Space UI.
        </p>
      </header>

      {/* Main Prose Content */}
      <article className="w-full prose prose-slate dark:prose-invert max-w-none prose-headings:scroll-m-24 prose-headings:tracking-tight prose-a:text-primary prose-a:no-underline hover:prose-a:underline">
        <section>
          <h2>1. Overview &amp; Scope</h2>
          <p>
            This Privacy Policy describes how <strong>Space UI</strong> (&ldquo;we&rdquo;, &ldquo;us&rdquo;, or
            &ldquo;our&rdquo;), accessible at <Link href="https://www.spaceui.one">https://www.spaceui.one</Link>,
            handles your information when you browse our documentation, explore interactive previews, copy registry
            components, or leave notes on the Community Wall.
          </p>
          <p>
            Space UI is an open-source React component distribution. We do not sell, monetize, or rent personal data.
            Our services are built to be privacy-friendly by design.
          </p>
        </section>

        <hr />

        <section>
          <h2>2. Information We Collect</h2>
          <p>
            We collect only the minimum information necessary to deliver our services, categorized into the following
            areas:
          </p>

          <h3>A. Third-Party Authentication (OAuth)</h3>
          <p>
            When you choose to authenticate using <strong>GitHub</strong> or <strong>Google</strong> (via Supabase
            Auth), we receive:
          </p>
          <ul>
            <li>
              <strong>Profile Information:</strong> Public display name, username, and avatar URL.
            </li>
            <li>
              <strong>Email Address:</strong> Used solely to associate and verify your session identity.
            </li>
            <li>
              <strong>Unique Account Identifier:</strong> An opaque string ID generated by the OAuth provider.
            </li>
          </ul>
          <p>
            We do not request or receive sensitive third-party account permissions, passwords, private repositories, or
            email message contents.
          </p>

          <h3>B. Community Wall Notes &amp; Submissions</h3>
          <p>
            When you post a note on our Community Wall, the submission data is stored in our database and made public on
            the canvas:
          </p>
          <ul>
            <li>Your message content.</li>
            <li>Your author display name and selected avatar (OAuth avatar or a Space UI avatar/squishmoji).</li>
            <li>Visual properties including card pattern index, rotation angle, and canvas coordinates.</li>
            <li>Creation timestamp.</li>
          </ul>

          <h3>C. Telemetry &amp; Performance Diagnostics</h3>
          <p>
            We use privacy-conscious analytics tools (<strong>PostHog</strong> and <strong>Vercel Analytics</strong>) to
            gather aggregate, non-identifying telemetry:
          </p>
          <ul>
            <li>Visited pages, referrer URLs, and device/browser category.</li>
            <li>Documentation interactions (such as copying an install command or switching code tabs).</li>
            <li>Client-side runtime error logs to resolve software bugs.</li>
          </ul>
        </section>

        <hr />

        <section>
          <h2>3. Cookies &amp; Local Storage</h2>
          <p>
            We do not use tracking pixels or advertising cookies. The browser cookies and local storage items we utilize
            are strictly functional:
          </p>
          <TypeTable
            type={{
              'sb-*-auth-token': {
                type: 'HTTP Cookie',
                description: 'Maintains your authenticated session state securely.',
                required: true,
              },
              'space-ui-layout-mode': {
                type: 'Cookie | LocalStorage',
                description: 'Remembers your layout mode choice (standard or split view).',
              },
              'space-ui-theme': {
                type: 'LocalStorage',
                description: 'Persists your light/dark mode and active brand accent color.',
              },
              'space-ui-package-manager': {
                type: 'LocalStorage',
                description: 'Stores your selected package manager (pnpm, npm, yarn, or bun) for install commands.',
              },
            }}
          />
        </section>

        <hr />

        <section>
          <h2>4. Third-Party Sub-processors</h2>
          <p>We rely on trusted infrastructure providers to operate the platform:</p>
          <ul>
            <li>
              <strong>Supabase:</strong> Cloud database hosting and authentication provider.
            </li>
            <li>
              <strong>Vercel:</strong> Application hosting, edge network, and serverless compute.
            </li>
            <li>
              <strong>PostHog:</strong> Privacy-friendly analytics and error monitoring.
            </li>
            <li>
              <strong>GitHub &amp; Google:</strong> OAuth 2.0 identity providers used exclusively for user sign-in.
            </li>
          </ul>
        </section>

        <hr />

        <section>
          <h2>5. Open Source Registry Privacy</h2>
          <p>
            All components, hooks, blocks, and primitives published in Space UI are licensed under the{' '}
            <strong>MIT License</strong>. None of our component code embeds telemetry, tracking scripts, or
            &ldquo;phone-home&rdquo; network requests. Once copied or installed in your project, the code runs
            completely offline and isolated within your own application stack.
          </p>
        </section>

        <hr />

        <section>
          <h2>6. Data Retention &amp; User Rights</h2>
          <p>Under GDPR, CCPA, and global privacy frameworks, you have full ownership of your personal data:</p>
          <ul>
            <li>
              <strong>Access &amp; Export:</strong> Request an export of your account data and posted community
              messages.
            </li>
            <li>
              <strong>Rectification:</strong> Correct or modify your account information.
            </li>
            <li>
              <strong>Right to Erasure:</strong> Request the deletion of your account and removal of any notes you
              published on the Community Wall.
            </li>
          </ul>
          <p>
            To submit an erasure or data inquiry, contact us directly at{' '}
            <a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a>.
          </p>
        </section>

        <hr />

        <section>
          <h2>7. Contact &amp; Updates</h2>
          <p>
            We may update this Privacy Policy from time to time. Changes become effective upon publication with a
            revised date at the top of this page.
          </p>
          <p>If you have any questions or requests, feel free to reach out:</p>
          <div className="not-prose flex flex-wrap gap-3 mt-4">
            <Button size="sm" render={<a href={`mailto:${siteConfig.email}`} />}>
              {siteConfig.email}
            </Button>
            <Button size="sm" render={<a href={siteConfig.links.github} target="_blank" rel="noreferrer" />}>
              GitHub Repository
            </Button>
          </div>
        </section>
      </article>

      {/* Docs Pager Navigation */}
      <DocsPager next={{ name: 'Terms of Service', url: '/terms' }} />
    </div>
  )
}
