/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "block-interactive-grid-hero-1": lazyRegistryComponent(
    () => import("@/registry/blocks/interactive-grid-hero/interactive-grid-hero-1/index.tsx"),
    {"cellSize":{"value":64,"options":{"Compact (48px)":48,"Standard (64px)":64,"Expanded (80px)":80}},"radius":{"value":"rounded","options":{"Square":"square","Rounded":"rounded","Full (Circle)":"full"}},"proximity":{"value":4,"options":{"Focused (3)":3,"Standard (4)":4,"Wide (5.5)":5.5}}},
  ),
};
