/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "components-spaceui-autoscale-input": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/autoscale-input/index.tsx"),
    {},
  ),
  "components-spaceui-avatar-extended": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/avatar-extended/index.tsx"),
    {},
  ),
  "components-spaceui-avatar-group": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/avatar-group/index.tsx"),
    {},
  ),
  "components-spaceui-bouncy-accordion": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/bouncy-accordion/index.tsx"),
    {},
  ),
  "components-spaceui-copy": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/copy/index.tsx"),
    {},
  ),
  "components-spaceui-date-selector": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/date-selector/index.tsx"),
    {},
  ),
  "components-spaceui-dirt-carousel": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/dirt-carousel/index.tsx"),
    {},
  ),
  "components-spaceui-filters": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/filters/index.tsx"),
    {},
  ),
  "components-spaceui-icon-stack": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/icon-stack/index.tsx"),
    {},
  ),
  "components-spaceui-image-dark": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/image-dark/index.tsx"),
    {},
  ),
  "components-spaceui-kanban": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/kanban/index.tsx"),
    {},
  ),
  "components-spaceui-liquid-metal-avatar": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/liquid-metal-avatar/index.tsx"),
    {},
  ),
  "components-spaceui-liquid-metal-button": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/liquid-metal-button/index.tsx"),
    {},
  ),
  "components-spaceui-liquid-metal-card": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/liquid-metal-card/index.tsx"),
    {},
  ),
  "components-spaceui-morph-icon": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/morph-icon/index.tsx"),
    {},
  ),
  "components-spaceui-notification-list": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/notification-list/index.tsx"),
    {},
  ),
  "components-spaceui-phone-input": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/phone-input/index.tsx"),
    {},
  ),
  "components-spaceui-pin-list": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/pin-list/index.tsx"),
    {},
  ),
  "components-spaceui-rating": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/rating/index.tsx"),
    {},
  ),
  "components-spaceui-resizable": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/resizable/index.tsx"),
    {},
  ),
  "components-spaceui-scrollspy": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/scrollspy/index.tsx"),
    {},
  ),
  "components-spaceui-section-scrollspy": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/section-scrollspy/index.tsx"),
    {},
  ),
  "components-spaceui-sortable": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/sortable/index.tsx"),
    {},
  ),
  "components-spaceui-status-badge": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/status-badge/index.tsx"),
    {},
  ),
  "components-spaceui-theme-toggle": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/theme-toggle/index.tsx"),
    {},
  ),
  "components-spaceui-timeline": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/timeline/index.tsx"),
    {},
  ),
  "components-spaceui-tournament-bracket": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/tournament-bracket/index.tsx"),
    {},
  ),
  "components-spaceui-user-presence-avatar": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/user-presence-avatar/index.tsx"),
    {},
  ),
  "components-spaceui-words-preloader": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/words-preloader/index.tsx"),
    {},
  ),
};
