/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "components-orb-bloop": lazyRegistryComponent(
    () => import("@/registry/components/orb/bloop/index.tsx"),
    {},
  ),
  "components-orb-generating": lazyRegistryComponent(
    () => import("@/registry/components/orb/generating/index.tsx"),
    {},
  ),
  "components-orb-loading": lazyRegistryComponent(
    () => import("@/registry/components/orb/loading/index.tsx"),
    {},
  ),
  "components-orb-smooth": lazyRegistryComponent(
    () => import("@/registry/components/orb/smooth/index.tsx"),
    {},
  ),
  "components-orb-thinking": lazyRegistryComponent(
    () => import("@/registry/components/orb/thinking/index.tsx"),
    {},
  ),
};
