/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "demo-c-orb-loading-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/orb/loading/c-orb-loading-01/index.tsx"),
    {"motionPreset":{"value":"morph","options":{"Morph":"morph","Fade":"fade","Scale":"scale","Blur":"blur","Flip":"flip"}},"size":{"value":48,"min":32,"max":96,"step":4},"speed":{"value":750,"min":300,"max":2000,"step":50},"radius":{"value":3,"min":0,"max":10,"step":1},"gap":{"value":3,"min":1,"max":8,"step":1},"showGhost":{"value":false}},
  ),
  "demo-c-orb-loading-02": lazyRegistryComponent(
    () => import("@/registry/demo/components/orb/loading/c-orb-loading-02/index.tsx"),
    {"state":{"value":"Building","options":{"Building":"Building","Thinking":"Thinking","Generating":"Generating","Searching":"Searching","Connecting":"Connecting"}},"detail":{"value":"Composing response from context"},"color":{"value":"text-foreground","options":{"Default":"text-foreground","Emerald":"text-emerald-500","Indigo":"text-indigo-500","Amber":"text-amber-500","Rose":"text-rose-500"}},"showShimmer":{"value":true}},
  ),
  "demo-c-orb-loading-03": lazyRegistryComponent(
    () => import("@/registry/demo/components/orb/loading/c-orb-loading-03/index.tsx"),
    {},
  ),
};
