/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "demo-c-fluid-distortion-image-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/fluid-distortion-image/c-fluid-distortion-image-01/index.tsx"),
    {"textureFile":{"type":"file","accept":"image/*","value":""},"revealStyle":{"value":"pixelate","options":{"Pixelate sweep":"pixelate","Blur morph":"blur"}},"distortionIntensity":{"value":0.02,"options":{"Subtle (0.01)":0.01,"Original (0.02)":0.02,"Intense (0.05)":0.05,"Extreme (0.09)":0.09}},"relaxationSpeed":{"value":0.95,"options":{"Fast (0.88)":0.88,"Standard (0.95)":0.95,"Trailing (0.98)":0.98}},"radius":{"value":8.96,"options":{"Small (5.0)":5,"Original (8.96)":8.96,"Large (14.0)":14}}},
  ),
};
