/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "demo-c-smooth-slider-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/smooth-slider/c-smooth-slider-01/index.tsx"),
    {"min":{"value":0,"min":0,"max":20,"step":1},"max":{"value":100,"min":60,"max":150,"step":1},"step":{"value":5,"min":1,"max":20,"step":1},"height":{"value":32,"min":16,"max":64,"step":2},"showTicks":{"value":true},"fillFrom":{"value":"#bae6fd"},"fillVia":{"value":"#e0e7ff"},"fillTo":{"value":"#60a5fa"}},
  ),
};
