/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "demo-c-fluid-crossfade-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/fluid-crossfade/c-fluid-crossfade-01/index.tsx"),
    {"imageSource":{"value":"url","options":{"Remote URL":"url","Upload File":"upload"}},"imageA":{"value":"https://cdn.spaceui.one/atom/samples/image-1.png","options":{"Landscape":"https://cdn.spaceui.one/atom/samples/image-1.png","Architecture":"https://cdn.spaceui.one/atom/samples/image-2.png"},"dependsOn":{"imageSource":"url"}},"imageFront":{"type":"file","accept":"image/*","value":"","dependsOn":{"imageSource":"upload"}},"imageB":{"value":"https://cdn.spaceui.one/atom/samples/image-2.png","options":{"Architecture":"https://cdn.spaceui.one/atom/samples/image-2.png","Portrait":"https://cdn.spaceui.one/atom/samples/image-3.png"},"dependsOn":{"imageSource":"url"}},"imageBack":{"type":"file","accept":"image/*","value":"","dependsOn":{"imageSource":"upload"}},"refractionStrength":{"value":0.85,"options":{"Subtle (0.4)":0.4,"Balanced (0.85)":0.85,"Intense (1.6)":1.6}},"ditherGrid":{"value":3,"options":{"Fine (2.0)":2,"Standard (3.0)":3,"Chunky (6.0)":6}},"pixelGridSize":{"value":240,"options":{"High-Res (320)":320,"Standard (240)":240,"Pixelated (120)":120}}},
  ),
};
