/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "demo-c-orb-thinking-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/orb/thinking/c-orb-thinking-01/index.tsx"),
    {"surface":{"value":"auto","options":{"Auto Theme":"auto","Ink (Dark)":"ink","Paper (Light)":"paper"}},"size":{"value":240,"min":120,"max":420,"step":10},"speed":{"value":1,"min":0.2,"max":2.5,"step":0.1},"scale":{"value":0.72,"min":0.3,"max":0.95,"step":0.02},"playback":{"value":"play","options":{"Play":"play","Pause":"pause"}}},
  ),
  "demo-c-orb-thinking-02": lazyRegistryComponent(
    () => import("@/registry/demo/components/orb/thinking/c-orb-thinking-02/index.tsx"),
    {"surface":{"value":"auto","options":{"Auto Theme":"auto","Ink (Dark)":"ink","Paper (Light)":"paper"}},"size":{"value":240,"min":120,"max":420,"step":10},"speed":{"value":1,"min":0.2,"max":2.5,"step":0.1},"scale":{"value":0.72,"min":0.3,"max":0.95,"step":0.02},"playback":{"value":"play","options":{"Play":"play","Pause":"pause"}}},
  ),
  "demo-c-orb-thinking-03": lazyRegistryComponent(
    () => import("@/registry/demo/components/orb/thinking/c-orb-thinking-03/index.tsx"),
    {"surface":{"value":"auto","options":{"Auto Theme":"auto","Ink (Dark)":"ink","Paper (Light)":"paper"}},"size":{"value":240,"min":120,"max":420,"step":10},"speed":{"value":1,"min":0.2,"max":2.5,"step":0.1},"scale":{"value":0.72,"min":0.3,"max":0.95,"step":0.02},"playback":{"value":"play","options":{"Play":"play","Pause":"pause"}}},
  ),
  "demo-c-orb-thinking-04": lazyRegistryComponent(
    () => import("@/registry/demo/components/orb/thinking/c-orb-thinking-04/index.tsx"),
    {"surface":{"value":"auto","options":{"Auto Theme":"auto","Ink (Dark)":"ink","Paper (Light)":"paper"}},"size":{"value":240,"min":120,"max":420,"step":10},"speed":{"value":1,"min":0.2,"max":2.5,"step":0.1},"scale":{"value":0.72,"min":0.3,"max":0.95,"step":0.02},"playback":{"value":"play","options":{"Play":"play","Pause":"pause"}}},
  ),
  "demo-c-orb-thinking-05": lazyRegistryComponent(
    () => import("@/registry/demo/components/orb/thinking/c-orb-thinking-05/index.tsx"),
    {"surface":{"value":"auto","options":{"Auto Theme":"auto","Ink (Dark)":"ink","Paper (Light)":"paper"}},"size":{"value":240,"min":120,"max":420,"step":10},"speed":{"value":1,"min":0.2,"max":2.5,"step":0.1},"scale":{"value":0.72,"min":0.3,"max":0.95,"step":0.02},"playback":{"value":"play","options":{"Play":"play","Pause":"pause"}}},
  ),
  "demo-c-orb-thinking-06": lazyRegistryComponent(
    () => import("@/registry/demo/components/orb/thinking/c-orb-thinking-06/index.tsx"),
    {"surface":{"value":"auto","options":{"Auto Theme":"auto","Ink (Dark)":"ink","Paper (Light)":"paper"}},"size":{"value":240,"min":120,"max":420,"step":10},"speed":{"value":1,"min":0.2,"max":2.5,"step":0.1},"scale":{"value":0.72,"min":0.3,"max":0.95,"step":0.02},"playback":{"value":"play","options":{"Play":"play","Pause":"pause"}}},
  ),
  "demo-c-orb-thinking-07": lazyRegistryComponent(
    () => import("@/registry/demo/components/orb/thinking/c-orb-thinking-07/index.tsx"),
    {"surface":{"value":"auto","options":{"Auto Theme":"auto","Ink (Dark)":"ink","Paper (Light)":"paper"}},"size":{"value":240,"min":120,"max":420,"step":10},"speed":{"value":1,"min":0.2,"max":2.5,"step":0.1},"scale":{"value":0.72,"min":0.3,"max":0.95,"step":0.02},"playback":{"value":"play","options":{"Play":"play","Pause":"pause"}}},
  ),
  "demo-c-orb-thinking-08": lazyRegistryComponent(
    () => import("@/registry/demo/components/orb/thinking/c-orb-thinking-08/index.tsx"),
    {"surface":{"value":"auto","options":{"Auto Theme":"auto","Ink (Dark)":"ink","Paper (Light)":"paper"}},"size":{"value":240,"min":120,"max":420,"step":10},"speed":{"value":1,"min":0.2,"max":2.5,"step":0.1},"scale":{"value":0.72,"min":0.3,"max":0.95,"step":0.02},"playback":{"value":"play","options":{"Play":"play","Pause":"pause"}}},
  ),
  "demo-c-orb-thinking-09": lazyRegistryComponent(
    () => import("@/registry/demo/components/orb/thinking/c-orb-thinking-09/index.tsx"),
    {"surface":{"value":"auto","options":{"Auto Theme":"auto","Ink (Dark)":"ink","Paper (Light)":"paper"}},"size":{"value":240,"min":120,"max":420,"step":10},"speed":{"value":1,"min":0.2,"max":2.5,"step":0.1},"scale":{"value":0.72,"min":0.3,"max":0.95,"step":0.02},"playback":{"value":"play","options":{"Play":"play","Pause":"pause"}}},
  ),
};
