/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "demo-c-orb-smooth-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/orb/smooth/c-orb-smooth-01/index.tsx"),
    {"textureSource":{"value":"url","options":{"Remote URL":"url","Upload File":"upload"}},"textureUrl":{"value":"https://avatars.spaceui.one/v1?name=space&variant=lumina&format=svg","dependsOn":{"textureSource":"url"}},"textureFile":{"type":"file","accept":"image/*","value":"","dependsOn":{"textureSource":"upload"}},"grain":{"value":true},"grainAnimated":{"value":true,"dependsOn":{"grain":true}},"grainOpacity":{"value":0.67,"min":0,"max":1,"step":0.05,"dependsOn":{"grain":true}},"watercolor":{"value":true},"watercolorStrength":{"value":0.5,"min":0,"max":1,"step":0.05,"dependsOn":{"watercolor":true}},"size":{"value":240,"min":120,"max":520,"step":10},"audioMode":{"value":"ambient","options":{"Ambient":"ambient","Microphone":"mic","Audio Track":"file"}},"audioSource":{"value":"url","options":{"Remote URL":"url","Upload File":"upload"},"dependsOn":{"audioMode":"file"}},"audioUrl":{"value":"https://cdn.pixabay.com/audio/2025/05/10/audio_3317d9a155.mp3","dependsOn":{"audioMode":"file","audioSource":"url"}},"audioFile":{"type":"file","accept":"audio/*","value":"","dependsOn":{"audioMode":"file","audioSource":"upload"}}},
  ),
};
