/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "demo-c-pixel-reveal-image-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/pixel-reveal-image/c-pixel-reveal-image-01/index.tsx"),
    {"textureFile":{"type":"file","accept":"image/*","value":""},"accentColor":{"value":"#ffe9a8","options":{"Aurum":"#ffe9a8","Mercury":"#f0f4f8","Iris":"#c9a6ff","Cobalt":"#93c5fd","Forge":"#fdba74","Jade":"#6ee7b7","Pearl":"#fafafa","White":"#ffffff","Black":"#000000"}},"gridDensity":{"value":38,"options":{"Fine (60)":60,"Standard (38)":38,"Chunky (20)":20}},"bandWidth":{"value":3.5,"options":{"Tight (2.0)":2,"Standard (3.5)":3.5,"Broad (6.0)":6}},"noiseIntensity":{"value":0.16,"options":{"Subtle (0.08)":0.08,"Balanced (0.16)":0.16,"Heavy (0.35)":0.35}},"trigger":{"value":"loop","options":{"Loop (Auto)":"loop","Hover":"hover","Scroll":"scroll"}}},
  ),
};
