/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "demo-c-morphing-text-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/morphing-text/c-morphing-text-01/index.tsx"),
    {"interval":{"value":2400,"options":{"Fast (1600ms)":1600,"Standard (2400ms)":2400,"Slow (3400ms)":3400}},"blurAmount":{"value":"10px","options":{"Subtle (6px)":"6px","Balanced (10px)":"10px","Deep (16px)":"16px"}},"springBounce":{"value":0.14,"options":{"Tight (0.08)":0.08,"Balanced (0.14)":0.14,"Playful (0.24)":0.24}},"pauseOnHover":{"value":true}},
  ),
  "demo-c-morphing-text-02": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/morphing-text/c-morphing-text-02/index.tsx"),
    {"interval":{"value":2800,"options":{"Fast (2000ms)":2000,"Standard (2800ms)":2800,"Relaxed (3800ms)":3800}},"blurAmount":{"value":"10px","options":{"Subtle (6px)":"6px","Balanced (10px)":"10px","Deep (16px)":"16px"}},"pauseOnHover":{"value":true}},
  ),
};
