/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "demo-c-orb-generating-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/orb/generating/c-orb-generating-01/index.tsx"),
    {"renderer":{"value":"css","options":{"CSS Keyframes":"css","Canvas 2D":"canvas"}},"size":{"value":240,"min":80,"max":420,"step":4},"depth":{"value":1,"min":0.4,"max":1.8,"step":0.05},"duration":{"value":2000,"min":600,"max":5000,"step":50},"stagger":{"value":100,"min":0,"max":300,"step":5},"pop":{"value":1.15,"min":1,"max":1.6,"step":0.01},"restOpacity":{"value":0.4,"min":0.1,"max":1,"step":0.05},"textSize":{"value":1.2,"min":0.7,"max":2.4,"step":0.05},"tracking":{"value":0,"min":-2,"max":8,"step":0.25},"text":{"value":"Generating"},"showText":{"value":true},"highlightColor":{"value":"#ffffff"},"haloColor":{"value":"#ad5fff"},"coreColor":{"value":"#471eec"},"haloColorAlt":{"value":"#d60a47"},"coreColorAlt":{"value":"#311e80"},"playback":{"value":"play","options":{"Play":"play","Pause":"pause"}}},
  ),
};
