/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "demo-c-silk-flare-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/shader/silk-flare/c-silk-flare-01/index.tsx"),
    {"color1":{"value":"#7c3aed"},"color2":{"value":"#6366f1"},"color3":{"value":"#a855f7"},"hotColor":{"value":"#38bdf8"},"heatOpacity":{"value":0.5,"min":0,"max":1,"step":0.05},"speed":{"value":0.8,"min":0,"max":3,"step":0.1},"animate":{"value":true},"grain":{"value":true}},
  ),
};
