/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "demo-c-blur-reveal-text-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/blur-reveal-text/c-blur-reveal-text-01/index.tsx"),
    {"text":{"value":"Great design is not just what looks good. It is how every detail feels alive."},"splitBy":{"value":"words","options":{"Words":"words","Characters":"characters"}},"direction":{"value":"up","options":{"Upward":"up","Downward":"down","Stationary":"none"}},"blurAmount":{"value":"12px","options":{"Subtle (6px)":"6px","Balanced (12px)":"12px","Deep (20px)":"20px"}},"stagger":{"value":0.05,"options":{"Fast (0.03s)":0.03,"Normal (0.05s)":0.05,"Deliberate (0.09s)":0.09}}},
  ),
};
