/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "demo-c-fluid-dither-crossfade-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/fluid-dither-crossfade/c-fluid-dither-crossfade-01/index.tsx"),
    {"imageFront":{"type":"file","accept":"image/*","value":""},"imageBack":{"type":"file","accept":"image/*","value":""},"revealStyle":{"value":"pixelate","options":{"Pixelate sweep":"pixelate","Blur morph":"blur","Stagger wipe":"stagger"}},"brushSize":{"value":0.3,"options":{"Subtle (0.3)":0.3,"Balanced (0.64)":0.64,"Broad (1.0)":1,"Huge (1.5)":1.5}},"pixelRes":{"value":150,"options":{"High Def (300)":300,"Standard (150)":150,"Retro (80)":80,"Low Bit (40)":40}},"pixelEdgeRes":{"value":80,"options":{"Fine Mask (120)":120,"Chunky Blocks (80)":80,"Giant Pixels (40)":40}},"distortionStrength":{"value":9.18,"options":{"Gentle (4.0)":4,"Original (9.18)":9.18,"Heavy (18.0)":18}},"ditherGrid":{"value":20,"options":{"Micro (8)":8,"Classic (20)":20,"Macro (40)":40}},"inkDissipation":{"value":0.926,"options":{"Fast Fade (0.88)":0.88,"Balanced (0.926)":0.926,"Persistent (0.97)":0.97}},"accentColor":{"value":"#ffe9a8","options":{"Aurum":"#ffe9a8","Mercury":"#f0f4f8","Iris":"#c9a6ff","Cobalt":"#93c5fd","Forge":"#fdba74","Jade":"#6ee7b7","Pearl":"#fafafa","White":"#ffffff","Black":"#000000"}}},
  ),
};
