/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "demo-c-textmoji-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/textmoji/c-textmoji-01/index.tsx"),
    {"text":{"value":"Ship your ideas faster 🚀 with Space UI 🫧🦄"},"source":{"value":"fluent","options":{"Fluent":"fluent","Apple":"apple","Twemoji":"twemoji","Blobmoji":"blobmoji","Noto":"noto"}}},
  ),
  "demo-c-textmoji-02": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/textmoji/c-textmoji-02/index.tsx"),
    {},
  ),
  "demo-c-textmoji-03": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/textmoji/c-textmoji-03/index.tsx"),
    {},
  ),
  "demo-c-textmoji-04": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/textmoji/c-textmoji-04/index.tsx"),
    {},
  ),
  "demo-c-textmoji-05": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/textmoji/c-textmoji-05/index.tsx"),
    {},
  ),
};
