/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "demo-c-pixel-reveal-text-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/pixel-reveal-text/c-pixel-reveal-text-01/index.tsx"),
    {"text":{"value":"Space UI 🤯❣️"},"edgeColor":{"value":"#ffe9a8","options":{"Aurum":"#ffe9a8","Mercury":"#f0f4f8","Iris":"#c9a6ff","Cobalt":"#93c5fd","Forge":"#fdba74","Jade":"#6ee7b7","Pearl":"#fafafa","White":"#ffffff","Black":"#000000"}},"pixelSize":{"value":4,"options":{"Fine (2px)":2,"Crisp (4px)":4,"Pixelated (8px)":8,"Blocky (14px)":14}},"fontSize":{"value":54,"options":{"Medium (36px)":36,"Large (54px)":54,"Display (72px)":72}},"speed":{"value":1,"options":{"Slow (0.6x)":0.6,"Normal (1x)":1,"Fast (1.5x)":1.5,"Turbo (2x)":2}},"trigger":{"value":"loop","options":{"Loop (Auto)":"loop","Hover":"hover","Scroll":"scroll"}}},
  ),
  "demo-c-pixel-reveal-text-02": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/pixel-reveal-text/c-pixel-reveal-text-02/index.tsx"),
    {},
  ),
};
