/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "lib-get-strict-context": lazyRegistryComponent(
    () => import("@/registry/lib/get-strict-context/index.tsx"),
    {},
  ),
  "lib-gpu-runtime": lazyRegistryComponent(
    () => import("@/registry/lib/gpu-runtime/index.ts"),
    {},
  ),
  "lib-next-image-url": lazyRegistryComponent(
    () => import("@/registry/lib/next-image-url/index.ts"),
    {},
  ),
  "lib-segmented-control": lazyRegistryComponent(
    () => import("@/registry/lib/segmented-control/index.ts"),
    {},
  ),
  "lib-utils": lazyRegistryComponent(
    () => import("@/registry/lib/utils/index.ts"),
    {},
  ),
};
