// This file is autogenerated by scripts/build-registry.ts
export const registryStats = {
  "components": 61,
  "primitives": 60,
  "blocks": 5,
  "templates": 1,
  "hooks": 82,
  "hooksOnly": 61,
  "hookComponents": 8,
  "hookUtils": 13
} as const;
