import type { Chip, ChipKey, Layout, AnimType, OgState, Preset } from './types'

export const LAYOUTS: { id: Layout; name: string; description: string }[] = [
  { id: 'editorial', name: 'Editorial', description: 'Classic clean balanced composition' },
  { id: 'centered', name: 'Centered', description: 'Symmetrical focus for announcements' },
  { id: 'split', name: 'Split', description: 'Two-column grid with right accents' },
  { id: 'bottom', name: 'Bottom stack', description: 'Anchored to bottom with floating header' },
  { id: 'panel', name: 'Glass panel', description: 'Frosted translucent glass card' },
  { id: 'banner', name: 'Banner', description: 'Horizontal strip layout' },
  { id: 'poster', name: 'Poster', description: 'Impactful typography with top badges' },
  { id: 'sidebar', name: 'Sidebar', description: 'Vertical dividing column' },
  { id: 'quote', name: 'Quote', description: 'Testimonial or callout with quote marks' },
  { id: 'ticket', name: 'Ticket', description: 'Dashed perforations & stub layout' },
  { id: 'corners', name: 'Corners', description: 'Content framed by corner badges' },
  { id: 'stack', name: 'Stack', description: 'Clean linear vertical hierarchy' },
]

export const CHIP_KEYS: { id: ChipKey; name: string }[] = [
  { id: 'badge', name: 'Badge' },
  { id: 'brand', name: 'Brand' },
  { id: 'title', name: 'Title' },
  { id: 'subtitle', name: 'Subtitle' },
  { id: 'tags', name: 'Tags' },
  { id: 'footer', name: 'Footer' },
]

export const chipOff = (over: Partial<Chip> = {}): Chip => ({
  on: false,
  bg: 'rgba(255,255,255,0.07)',
  border: 'rgba(255,255,255,0.16)',
  text: '',
  radius: 999,
  padX: 18,
  padY: 10,
  blur: 0,
  ...over,
})

export const ANIMS: AnimType[] = ['fade-up', 'zoom', 'blur-in', 'slide', 'reveal', 'pop']

export const SIZES: { id: string; name: string; w: number; h: number; ratio: string }[] = [
  { id: 'og', name: 'OG Card', w: 1200, h: 630, ratio: '1.91:1' },
  { id: 'square', name: 'Square', w: 1080, h: 1080, ratio: '1:1' },
  { id: 'wide', name: 'Wide (16:9)', w: 1920, h: 1080, ratio: '16:9' },
]

/**
 * Proportionally scales typographic sizes, paddings, and radii when switching card dimensions
 * so that card designs maintain visual balance without shrinking or overflowing.
 */
export function applySizeScale(prev: OgState, newW: number, newH: number): OgState {
  if (prev.width === newW && prev.height === newH) return prev
  const oldArea = prev.width * prev.height
  const newArea = newW * newH
  if (oldArea <= 0 || newArea <= 0) {
    return { ...prev, width: newW, height: newH }
  }
  const ratio = Math.sqrt(newArea / oldArea)
  const scale = (val: number, min: number, max: number) => Math.min(max, Math.max(min, Math.round(val * ratio)))

  const scaleChip = (c: Chip): Chip => ({
    ...c,
    padX: scale(c.padX, 6, 80),
    padY: scale(c.padY, 4, 60),
    radius: scale(c.radius, 0, 999),
  })

  return {
    ...prev,
    width: newW,
    height: newH,
    titleSize: scale(prev.titleSize, 24, 200),
    subtitleSize: scale(prev.subtitleSize, 14, 80),
    brandSize: scale(prev.brandSize, 14, 60),
    tagsSize: scale(prev.tagsSize, 10, 50),
    footerSize: scale(prev.footerSize, 10, 50),
    badgeSize: scale(prev.badgeSize, 12, 50),
    logoSize: scale(prev.logoSize, 20, 160),
    padding: scale(prev.padding, 16, 200),
    radius: scale(prev.radius, 0, 100),
    showcaseSize: scale(prev.showcaseSize, 24, 120),
    showcaseGap: scale(prev.showcaseGap, 6, 40),
    chips: {
      badge: scaleChip(prev.chips.badge),
      brand: scaleChip(prev.chips.brand),
      title: scaleChip(prev.chips.title),
      subtitle: scaleChip(prev.chips.subtitle),
      tags: scaleChip(prev.chips.tags),
      footer: scaleChip(prev.chips.footer),
    },
  }
}

export function cloneChips(c: Record<ChipKey, Chip>): Record<ChipKey, Chip> {
  return Object.fromEntries(Object.entries(c).map(([k, v]) => [k, { ...v }])) as Record<ChipKey, Chip>
}

export const DEFAULT_OG_STATE: OgState = {
  brand: 'Space UI / Avatars',
  tags: 'React · Next.js · TypeScript',
  title: 'Control your interface down to the atom',
  subtitle: '420 primitives, 180 composed patterns and 40 templates driven by one variable layer.',
  footer: 'spaceui.one',
  badge: 'npm i @usespaceui/avatars',

  width: 1200,
  height: 630,

  bgMode: 'orbs',
  bgBase: 'rgb(9, 9, 9)',
  bgFrom: 'rgb(39, 112, 234)',
  bgVia: 'rgb(6, 196, 248)',
  bgTo: 'rgb(12, 191, 249)',
  glow: 'rgb(26, 139, 191)',
  angle: 135,

  bgBlur: 10,
  bgInset: 10,
  bgScale: 110,

  orbBlur: 90,
  orbOpacity: 60,
  orbSize: 100,
  grain: 0,
  vignette: 0,
  bgImage: '',
  bgImageDim: 40,

  meshShader: 'mesh',
  meshEffect: 'max',
  meshWarp: 26,
  meshDither: 10,
  meshNoise: 8,
  meshScan: 8,
  meshSteps: 10,
  meshGrid: 2,
  meshScale: 100,
  meshContrast: 100,
  meshBlend: 100,

  titleColor: 'rgb(255, 255, 255)',
  titleAccentColor: 'rgb(2, 132, 199)',
  subtitleColor: 'rgba(255,255,255,0.66)',
  mutedColor: 'rgba(255,255,255,0.6)',
  titleSize: 82,
  titleWeight: 600,
  titleTracking: -7.2,
  titleLeading: 0.9,
  subtitleSize: 28,
  brandSize: 28,
  tagsSize: 20,
  footerSize: 22,

  badgeStyle: 'squircle',
  badgeSize: 22,
  badgeMono: true,

  showTechBadges: false,
  techBadges: ['laravel', 'vue', 'react', 'ts'],

  logoSize: 44,
  logoGap: 18,
  logoUrl: '',
  radius: 0,
  padding: 64,

  layout: 'editorial',
  align: 'left',

  showBrand: true,
  showTags: true,
  showSubtitle: true,
  showFooter: true,
  showBadge: true,
  showLogo: true,

  showcaseOn: false,
  showcaseType: 'flags',
  showcaseLayout: 'cloud',
  showcaseShape: 'circle',
  showcaseCount: 22,
  showcaseSize: 56,
  showcaseGap: 16,
  showcaseWave: false,

  animOn: false,
  animType: 'fade-up',
  animDuration: 2.4,
  animStagger: 0.12,
  animFps: 25,
  animHold: 0.8,
  animBgDrift: 40,

  chips: {
    brand: chipOff(),
    tags: chipOff(),
    title: chipOff({ radius: 28, padX: 28, padY: 18 }),
    subtitle: chipOff({ radius: 24, padX: 24, padY: 16 }),
    footer: chipOff(),
    badge: chipOff({
      on: true,
      bg: 'rgba(255,255,255,0.06)',
      border: 'rgba(255,255,255,0.18)',
      text: 'rgba(255,255,255,0.85)',
      radius: 20,
      padX: 22,
      padY: 12,
    }),
  },
}

export const PRESETS: Preset[] = [
  {
    id: 'blade-flags',
    name: 'Blade Flags (Showcase)',
    patch: {
      brand: 'Blade UI Kit',
      badge: 'v1.4.0',
      title: 'Blade {Flags}',
      subtitle: 'A package to easily make use of SVG flags in your Laravel Blade views.',
      footer: 'blade-ui-kit.com/blade-flags',
      tags: 'Laravel · Blade · Icons',
      layout: 'split',
      align: 'left',
      bgMode: 'solid',
      bgBase: 'rgb(255, 255, 255)',
      titleColor: 'rgb(15, 23, 42)',
      titleAccentColor: 'rgb(2, 132, 199)',
      subtitleColor: 'rgb(100, 116, 139)',
      mutedColor: 'rgb(148, 163, 184)',
      titleSize: 84,
      subtitleSize: 26,
      brandSize: 24,
      showBrand: true,
      showBadge: false,
      showLogo: true,
      showFooter: true,
      showTags: false,
      showTechBadges: true,
      techBadges: ['laravel', 'vue', 'react', 'ts'],
      showcaseOn: true,
      showcaseType: 'flags',
      showcaseLayout: 'cloud',
      showcaseShape: 'circle',
      showcaseCount: 24,
      showcaseSize: 64,
      showcaseGap: 16,
      showcaseWave: false,
    },
    chips: {
      badge: chipOff(),
      brand: chipOff(),
      title: chipOff(),
      subtitle: chipOff(),
      tags: chipOff(),
      footer: chipOff(),
    },
  },
  {
    id: 'tabler-flags',
    name: 'Tabler Flags Shelf',
    patch: {
      brand: 'Tabler Icons',
      badge: '250+ SVG Flags',
      title: 'Explore over {250+} optimized country flags',
      subtitle: 'Free and open source SVG flag icons for your next project, tailored for modern web apps.',
      footer: 'tabler.io/flags',
      tags: 'SVG · Country · Open Source',
      layout: 'centered',
      align: 'center',
      bgMode: 'solid',
      bgBase: 'rgb(248, 250, 252)',
      titleColor: 'rgb(15, 23, 42)',
      titleAccentColor: 'rgb(37, 99, 235)',
      subtitleColor: 'rgb(100, 116, 139)',
      mutedColor: 'rgb(148, 163, 184)',
      titleSize: 58,
      subtitleSize: 20,
      showBrand: true,
      showBadge: true,
      badgeStyle: 'squircle',
      badgeMono: false,
      showFooter: true,
      showTags: true,
      showTechBadges: false,
      showcaseOn: true,
      showcaseType: 'flags',
      showcaseLayout: 'shelf',
      showcaseShape: 'squircle',
      showcaseCount: 27,
      showcaseSize: 52,
      showcaseGap: 18,
      showcaseWave: true,
    },
    chips: {
      badge: {
        on: true,
        bg: 'rgb(255, 255, 255)',
        border: 'rgba(0, 0, 0, 0.08)',
        text: 'rgb(15, 23, 42)',
        radius: 12,
        padX: 18,
        padY: 8,
        blur: 0,
      },
      brand: chipOff(),
      title: chipOff(),
      subtitle: chipOff(),
      tags: chipOff(),
      footer: chipOff(),
    },
  },
  {
    id: 'avatar-cloud',
    name: 'Avatar Cloud',
    patch: {
      brand: 'Space UI / Avatars',
      badge: '@usespaceui/avatars',
      title: 'Generate distinct {identicons} at scale',
      subtitle: 'Deterministic, theme-aware avatars rendered directly in SVG and Canvas.',
      footer: 'spaceui.one/avatars',
      tags: 'Design System · React',
      layout: 'split',
      align: 'left',
      bgMode: 'gradient',
      bgBase: 'rgb(10, 15, 29)',
      bgFrom: 'rgb(56, 189, 248)',
      bgVia: 'rgb(129, 140, 248)',
      bgTo: 'rgb(192, 132, 252)',
      glow: 'rgb(99, 102, 241)',
      titleColor: 'rgb(255, 255, 255)',
      titleAccentColor: 'rgb(56, 189, 248)',
      subtitleColor: 'rgba(255, 255, 255, 0.7)',
      mutedColor: 'rgba(255, 255, 255, 0.5)',
      titleSize: 76,
      subtitleSize: 24,
      showBrand: true,
      showBadge: true,
      badgeStyle: 'squircle',
      badgeMono: true,
      showFooter: true,
      showTags: false,
      showTechBadges: false,
      showcaseOn: true,
      showcaseType: 'avatars',
      showcaseLayout: 'cloud',
      showcaseShape: 'circle',
      showcaseCount: 22,
      showcaseSize: 64,
      showcaseGap: 16,
      showcaseWave: false,
    },
    chips: {
      badge: {
        on: true,
        bg: 'rgba(255, 255, 255, 0.08)',
        border: 'rgba(255, 255, 255, 0.18)',
        text: 'rgb(255, 255, 255)',
        radius: 16,
        padX: 20,
        padY: 10,
        blur: 10,
      },
      brand: chipOff(),
      title: chipOff(),
      subtitle: chipOff(),
      tags: chipOff(),
      footer: chipOff(),
    },
  },
  {
    id: 'squish-cloud',
    name: 'Squishmoji Fun',
    patch: {
      brand: 'Space UI / Squishmoji',
      badge: '@usespaceui/squishmoji',
      title: 'Expressive {emoji avatars} with personality',
      subtitle: 'Playful, interactive SVGs with dynamic expressions and organic shapes.',
      footer: 'spaceui.one/squishmoji',
      tags: 'React · Animation · SVG',
      layout: 'split',
      align: 'left',
      bgMode: 'gradient',
      bgBase: 'rgb(15, 12, 41)',
      bgFrom: 'rgb(244, 63, 94)',
      bgVia: 'rgb(249, 115, 22)',
      bgTo: 'rgb(234, 179, 8)',
      glow: 'rgb(244, 63, 94)',
      titleColor: 'rgb(255, 255, 255)',
      titleAccentColor: 'rgb(254, 240, 138)',
      subtitleColor: 'rgba(255, 255, 255, 0.75)',
      mutedColor: 'rgba(255, 255, 255, 0.55)',
      titleSize: 76,
      subtitleSize: 24,
      showBrand: true,
      showBadge: true,
      badgeStyle: 'squircle',
      badgeMono: true,
      showFooter: true,
      showTags: false,
      showTechBadges: false,
      showcaseOn: true,
      showcaseType: 'squishmoji',
      showcaseLayout: 'cloud',
      showcaseShape: 'squircle',
      showcaseCount: 22,
      showcaseSize: 64,
      showcaseGap: 16,
      showcaseWave: false,
    },
    chips: {
      badge: {
        on: true,
        bg: 'rgba(255, 255, 255, 0.12)',
        border: 'rgba(255, 255, 255, 0.22)',
        text: 'rgb(255, 255, 255)',
        radius: 16,
        padX: 20,
        padY: 10,
        blur: 10,
      },
      brand: chipOff(),
      title: chipOff(),
      subtitle: chipOff(),
      tags: chipOff(),
      footer: chipOff(),
    },
  },
  {
    id: 'tech-ecosystem',
    name: 'Tech Ecosystem',
    patch: {
      brand: 'Modern Web Stack',
      badge: 'Open Source',
      title: 'Built with {modern} frameworks',
      subtitle: 'Fully typed, hyper-optimized components and tools built for Next.js, Vue, and Vite.',
      footer: 'spaceui.one',
      tags: 'Fullstack · Frameworks',
      layout: 'split',
      align: 'left',
      bgMode: 'solid',
      bgBase: 'rgb(255, 255, 255)',
      titleColor: 'rgb(15, 23, 42)',
      titleAccentColor: 'rgb(99, 102, 241)',
      subtitleColor: 'rgb(100, 116, 139)',
      mutedColor: 'rgb(148, 163, 184)',
      titleSize: 78,
      subtitleSize: 24,
      showBrand: true,
      showBadge: false,
      showLogo: true,
      showFooter: true,
      showTags: false,
      showTechBadges: true,
      techBadges: ['nextjs', 'react', 'ts', 'tailwind', 'vite'],
      showcaseOn: true,
      showcaseType: 'tech',
      showcaseLayout: 'cloud',
      showcaseShape: 'squircle',
      showcaseCount: 20,
      showcaseSize: 64,
      showcaseGap: 18,
      showcaseWave: false,
    },
    chips: {
      badge: chipOff(),
      brand: chipOff(),
      title: chipOff(),
      subtitle: chipOff(),
      tags: chipOff(),
      footer: chipOff(),
    },
  },
  {
    id: 'lapis-orbs',
    name: 'Lapis orbs',
    patch: {
      bgMode: 'orbs',
      bgBase: 'rgb(9, 9, 9)',
      bgFrom: 'rgb(39, 112, 234)',
      bgVia: 'rgb(6, 196, 248)',
      glow: 'rgb(26, 139, 191)',
      bgTo: 'rgb(12, 191, 249)',
      orbBlur: 90,
      orbOpacity: 60,
      orbSize: 100,
      titleSize: 82,
      titleTracking: -7.2,
      titleLeading: 0.9,
      titleColor: 'rgb(255, 255, 255)',
      subtitleColor: 'rgba(255,255,255,0.66)',
      mutedColor: 'rgba(255,255,255,0.6)',
      badgeStyle: 'pill',
      badgeMono: false,
    },
    chips: {
      badge: {
        on: true,
        bg: 'rgba(255,255,255,0.06)',
        border: 'rgba(255,255,255,0.18)',
        text: 'rgba(255,255,255,0.85)',
      },
    },
  },
  {
    id: 'deep-gradient',
    name: 'Deep gradient',
    patch: {
      bgMode: 'gradient',
      bgFrom: 'rgb(26, 79, 214)',
      bgVia: 'rgb(5, 10, 20)',
      bgTo: 'rgb(13, 111, 128)',
      glow: 'rgb(30, 127, 146)',
      angle: 115,
      titleSize: 78,
      titleTracking: -3,
      titleLeading: 1.05,
      titleColor: 'rgb(255, 255, 255)',
      subtitleColor: 'rgb(195, 204, 214)',
      mutedColor: 'rgb(147, 161, 174)',
      badgeStyle: 'squircle',
      badgeMono: true,
    },
    chips: {
      badge: {
        on: true,
        bg: 'rgb(18, 33, 43)',
        text: 'rgb(230, 237, 243)',
        border: 'rgba(230,237,243,0.2)',
        radius: 20,
      },
    },
  },
  {
    id: 'soft-blur',
    name: 'Soft blur',
    patch: {
      bgMode: 'blur',
      bgFrom: 'rgb(18, 48, 107)',
      bgVia: 'rgb(11, 20, 36)',
      bgTo: 'rgb(26, 79, 214)',
      glow: 'rgb(46, 197, 211)',
      angle: 135,
      bgBlur: 26,
      bgInset: 10,
      bgScale: 118,
      titleSize: 80,
      titleTracking: -4,
      titleLeading: 0.95,
      titleColor: 'rgb(255, 255, 255)',
      subtitleColor: 'rgba(255,255,255,0.72)',
      mutedColor: 'rgba(255,255,255,0.6)',
      badgeStyle: 'squircle',
      badgeMono: true,
    },
    chips: {
      badge: { on: true, bg: 'rgba(255,255,255,0.1)', text: 'rgb(255, 255, 255)', border: 'rgba(255,255,255,0.25)' },
    },
  },
  {
    id: 'ink',
    name: 'Ink minimal',
    patch: {
      bgMode: 'solid',
      bgBase: 'rgb(8, 9, 10)',
      glow: 'rgb(31, 41, 55)',
      titleSize: 86,
      titleWeight: 600,
      titleTracking: -6,
      titleLeading: 0.92,
      titleColor: 'rgb(245, 247, 250)',
      subtitleColor: 'rgba(245,247,250,0.6)',
      mutedColor: 'rgba(245,247,250,0.45)',
      badgeStyle: 'pill',
      badgeMono: true,
    },
    chips: {
      badge: {
        on: true,
        bg: 'rgba(255,255,255,0.04)',
        text: 'rgba(255,255,255,0.8)',
        border: 'rgba(255,255,255,0.14)',
      },
    },
  },
  {
    id: 'paper',
    name: 'Paper light',
    patch: {
      bgMode: 'solid',
      bgBase: 'rgb(244, 242, 238)',
      glow: 'rgb(201, 214, 255)',
      titleSize: 80,
      titleTracking: -5,
      titleLeading: 0.95,
      titleColor: 'rgb(16, 20, 24)',
      subtitleColor: 'rgba(16,20,24,0.65)',
      mutedColor: 'rgba(16,20,24,0.5)',
      badgeStyle: 'squircle',
      badgeMono: true,
    },
    chips: {
      badge: { on: true, bg: 'rgb(16, 20, 24)', text: 'rgb(244, 242, 238)', border: 'rgba(16,20,24,0.15)', radius: 18 },
    },
  },
  {
    id: 'sunset',
    name: 'Sunset orbs',
    patch: {
      bgMode: 'orbs',
      bgBase: 'rgb(11, 7, 9)',
      bgFrom: 'rgb(255, 95, 109)',
      bgVia: 'rgb(255, 195, 113)',
      glow: 'rgb(192, 38, 211)',
      bgTo: 'rgb(249, 115, 22)',
      orbBlur: 110,
      orbOpacity: 55,
      orbSize: 115,
      titleSize: 84,
      titleTracking: -6,
      titleLeading: 0.92,
      titleColor: 'rgb(255, 247, 237)',
      subtitleColor: 'rgba(255,247,237,0.7)',
      mutedColor: 'rgba(255,247,237,0.55)',
      badgeStyle: 'squircle',
      badgeMono: true,
    },
    chips: {
      badge: {
        on: true,
        bg: 'rgba(0,0,0,0.35)',
        text: 'rgb(255, 247, 237)',
        border: 'rgba(255,247,237,0.25)',
        radius: 22,
      },
    },
  },
]

const KEEP: (keyof OgState)[] = [
  'brand',
  'tags',
  'title',
  'subtitle',
  'footer',
  'badge',
  'width',
  'height',
  'layout',
  'align',
  'logoUrl',
  'bgImage',
  'showBrand',
  'showTags',
  'showSubtitle',
  'showFooter',
  'showBadge',
  'showLogo',
  'animOn',
  'animType',
  'animDuration',
  'animStagger',
  'animFps',
  'animHold',
  'animBgDrift',
]

export function presetState(p: Preset, prev: OgState): OgState {
  const base = { ...DEFAULT_OG_STATE, chips: cloneChips(DEFAULT_OG_STATE.chips) } as OgState
  KEEP.forEach((k) => ((base as unknown as Record<string, unknown>)[k as string] = prev[k]))
  const next = { ...base, ...p.patch } as OgState
  const chips = Object.fromEntries(CHIP_KEYS.map((c) => [c.id, chipOff()])) as Record<ChipKey, Chip>
  chips.title = chipOff({ radius: 28, padX: 28, padY: 18 })
  chips.subtitle = chipOff({ radius: 24, padX: 24, padY: 16 })
  if (p.chips) {
    ;(Object.keys(p.chips) as ChipKey[]).forEach((k) => {
      chips[k] = { ...chips[k], ...p.chips![k] }
    })
  }
  next.chips = chips
  return next
}

export function presetPreview(p: Preset): OgState {
  return presetState(p, DEFAULT_OG_STATE)
}

export const easeOut = (t: number) => 1 - Math.pow(1 - t, 3)
export const easeSmooth = (t: number) => (t <= 0 ? 0 : t >= 1 ? 1 : 1 - Math.pow(2, -10 * t))
export const clamp01 = (v: number) => Math.max(0, Math.min(1, v))
export const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms))
